### PR TITLE
Pycord module name fix

### PR DESCRIPTION
**Pull request by AmashiSenpai**
I Literally just changed the import name from discord to pycord.

everything works the same except instead of 
```py
import discord
```
its
```py
import pycord
```

### CODE REVIEW

**Comment by plun1331** [comment]
If they wanted this done it would have been done by now

**Comment by krittick** [comment]
This would be a massive breaking change and one we decided against implementing early on when this fork was created. We'll be keeping the existing namespace for now.

**Comment by AmashiSenpai** [comment]
> If they wanted this done it would have been done by now

what idiot goes through and makes 286 changes where they're just replacing the word discord with pycord.

**Comment by plun1331** [comment]
> > If they wanted this done it would have been done by now
> 
> what idiot goes through and makes 286 changes where they're just replacing the word discord with pycord.

someone who knows how to use the `Replace` function in their IDE

**Pull request closed without merging**
