### PR TITLE
Add library-level limit enforcement for Embed attributes

### PR DESCRIPTION
**Pull request by krittick**
## Summary

This adds library-level enforcement of various Embed limits, similar to the changes made in #1065.

## Checklist

- [x] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting, examples, ...)

### CODE REVIEW

**Comment by jab416171** [comment]
There's also the limit where the sum of `title`, `description`, `field.name`, `field.value`, `footer.text`, and `author.name` across all embeds can't exceed 6000

**Comment by krittick** [comment]
> There's also the limit where the sum of `title`, `description`, `field.name`, `field.value`, `footer.text`, and `author.name` across all embeds can't exceed 6000

That's true, though a bit more complex to implement. Open to suggestions though.

**Comment by jab416171** [comment]
> That's true, though a bit more complex to implement. Open to suggestions though.

At a minimum you could enforce it on a single embed, and a helper method to get the total length would make it easier to verify on multiple embeds (like in message.send)

**Comment by krittick** [comment]
> > That's true, though a bit more complex to implement. Open to suggestions though.
> 
> At a minimum you could enforce it on a single embed, and a helper method to get the total length would make it easier to verify on multiple embeds (which you could check in message.send for example)

Hrm, now you've got me thinking on an idea. Moving to draft for now. :)

**Comment by Lulalaby** [comment]
Stale

**Pull request closed without merging**
