### PR TITLE
fix: add user argument to paginator.edit

### LINKED ISSUE #2381: Paginator author check
### Summary

Paginator.__init__() got an unexpected keyword argument 'user'

### Reproduction Steps

create a paginator, use the author_check function and edit the paginator

### Minimal Reproducible Code

```python
paginator = pages.Paginator(pages=pages, author_check=True, custom_view=View,  user=interaction.user​​ )​
await paginator.edit(interaction.message)
```

### Expected Results

It should just work as in the doc user is an attribute of pages.Paginator so we should be able to edit it like this because if we can't, author_check is useless, no user will never be able to interact since the user is the bot himself

### Actual Results

Paginator.__init__() got an unexpected keyword argument 'user'

### Intents

all

### System Information

- Python v3.11.4-final
- py-cord v2.5.None-final
- aiohttp v3.9.3

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by NeloBlivion**
## Summary

Fixes #2381 
`Paginator.edit` sets `self.user` to the message author... but since you can only edit your own messages, `user` is set to the bot and so breaks author_check. This changes it so you can specify any user for paginator.edit, otherwise uses the existing user if it was already set.

## Information

- [x] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed).
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting,
      examples, ...).

## Checklist

- [x] I have searched the open pull requests for duplicates.
- [x] If code changes were made then they have been tested.
  - [x] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why.
- [x] I have updated the changelog to include these changes.

### CODE REVIEW

**Comment by Revnoplex** [comment]
Will this fix #1877?

**Comment by Dorukyum** [comment]
As this adds a new parameter, we could have a changelog entry under the "Added" section too.

**Comment by Revnoplex** [comment]
This should fix #1877 too? As the now dead pr #2105 talked about fixing the exact same missing feature/bug related to both #1877 and #2381

**Comment by Lulalaby** [comment]
Please stop asking around, if it fixes that, we'll link it on merge

**Review by Lulalaby — DISMISSED** [review]

**Review by plun1331 — APPROVED** [review]

**Pull request merged**
