### PR TITLE
fix: owner_id showing None

### PR DESCRIPTION
**Pull request by NotNalin**
## Summary

This pull request fixes an issue where `owner_id` would return None and `owner_ids` would return `set()` instead of actually returning the owner id 

As a temporary fix i had to run `bot.is_owner(<id>)` to fix this 

This pull request now uses code from `is_owner()` to fetch the owner ids 

## Information

- [x] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed).
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting,
      examples, ...).

## Checklist

- [ ] I have searched the open pull requests for duplicates.
- [x] If code changes were made then they have been tested.
  - [ ] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why.

### CODE REVIEW

**Comment by Dorukyum** [comment]
I don't think this information is supposed to be fetched automatically, rather these attributes are set while initializing the bot and used in checks and stuff. Application information can still be viewed through `bot.application_info`.

**Comment by Lulalaby** [comment]
> I don't think this information is supposed to be fetched automatically, rather these attributes are set while initializing the bot and used in checks and stuff. Application information can still be viewed through `bot.application_info`.

I kinda believe it's the right way tho. I remember doing similar on startup because we only get a partial application on startup.
I might be wrong tho.

**Comment by plun1331** [comment]
`owner_id` and `owner_ids` are not supposed to be automatically populated until `is_owner()` is called:
https://docs.pycord.dev/en/master/api/clients.html#discord.Bot.owner_id

**Comment by Lulalaby** [comment]
Wouldn't harm tho to auto fill

**Comment by Dorukyum** [comment]
It would harm, it's an extra API call.
If anyone wants it filled automatically they can just add a line to their startup flow.

**Comment by Lulalaby** [comment]
I believe we should request the application info on startup always one time. But whatever

**Comment by Dorukyum** [comment]
I, for one, don't want pycord to make an API request for something my bot doesn't need. I think we should keep this opt-in, the docs already warn users about the situation.

**Comment by Lulalaby** [comment]
Ok agreed

**Pull request closed without merging**
