### PR TITLE
fix: run only local hooks for `SlashCommandGroup`

### LINKED ISSUE #2134: bot.before_invoke function runs twice with slash sub commands causing a whole bunch of issues
### Summary

the bot.before_invoke function gets called twice during the invocation of a slash sub command

### Reproduction Steps

This seems to only occur on master and not stable 2.4.1
1. Have a pre-invocation function with the `@bot.before_invoke` decorator
2. Have any slash command group
3. add a print statement to the pre-invocation function or add context.defer()
4. print statement will print twice or `InteractionResponded` will be raised

### Minimal Reproducible Code

```python
# in main file
#...

client: bridge.Bot = bridge.Bot(command_prefix=config.prefix, intents=intents, description=bot_desc, help_command=information.RevnobotHelp3(), debug_guilds=config.slash_guilds,max_messages=10**3, enable_debug_events=config.debug_mode)

# ...

@client.before_invoke
async def pre_invocation(ctx):
    print("i executed")

# in cog 

test_group = discord.SlashCommandGroup('test-group', "Hello Worlds")

@test_group.command(name="test1", description="Hello World 1")
@commands.cooldown(**config.default_cooldown_options)
@commands.bot_has_permissions(send_messages=True, attach_files=True)
async def test_1(self, ctx: discord.ApplicationContext):
    await ctx.respond("Hello World 1")
```

### Expected Results

`i executed` should only print once meaning

### Actual Results

`i executed` prints twice
or the following traceback if you use ctx.defer()
```python
  File "Revnobot/venv/lib/python3.11/site-packages/discord/commands/core.py", line 131, in wrapped
    ret = await coro(arg)
          ^^^^^^^^^^^^^^^

  File "Revnobot/venv/lib/python3.11/site-packages/discord/commands/core.py", line 1363, in _invoke
    await command.invoke(ctx)

  File "Revnobot/venv/lib/python3.11/site-packages/discord/commands/core.py", line 378, in invoke
    await self.prepare(ctx)

  File "Revnobot/venv/lib/python3.11/site-packages/discord/commands/core.py", line 310, in prepare
    await self.call_before_hooks(ctx)

  File "Revnobot/venv/lib/python3.11/site-packages/discord/commands/core.py", line 535, in call_before_hooks
    await hook(ctx)

  File "Revnobot/main.py", line 116, in pre_invocation
    await utils.pre_invocation(ctx)

  File "Revnobot/utils.py", line 147, in pre_invocation
    await ctx.defer()

  File "Revnobot/venv/lib/python3.11/site-packages/discord/ext/bridge/context.py", line 113, in defer
    return await self._defer(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "Revnobot/venv/lib/python3.11/site-packages/discord/ext/bridge/context.py", line 149, in _defer
    return await self._get_super("defer")(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "Revnobot/venv/lib/python3.11/site-packages/discord/interactions.py", line 705, in defer
    raise InteractionResponded(self._parent)
```

### Intents

all

### System Information

- Python v3.11.3-final
- py-cord v2.4.1-final
- aiohttp v3.8.4
- system info: Linux 6.3.6-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 05 Jun 2023 15:12:57 +0000

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by Om1609**
## Summary

Fixes bot and cog `before_invoke` hooks being called twice for subcommands (once with `ctx.command` set to the group, and once with `ctx.command` set to the subcommand). Fixes #2134 as discussed in the discord server.

This bug originally arised due to #2091 cleaning up the `prepare` logic. I personally would have considered a feature rather than a bug.

## Information

- [x] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed).
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting,
      examples, ...).

## Checklist

- [x] I have searched the open pull requests for duplicates.
- [x] If code changes were made then they have been tested.
  - [ ] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why.
- [ ] I have updated the changelog to include these changes.

### CODE REVIEW

**Comment by Lulalaby** [comment]
Changelog

**Review by Lulalaby — APPROVED** [review]

**Review by JustaSqu1d — CHANGES_REQUESTED** [review]
`type: ignore` comments were used but lacked additional rationale (unless I am missing something).

**Comment by Om1609** [comment]
> `type: ignore` comments were used but lacked additional rationale (unless I am missing something).

I just copy pasted the methods from `ApplicationCommand` and removed the Cog and Bot scoped hooks. The `type: ignore` comments were used there too. Idk why they are used

**Comment by Lulalaby** [comment]
then we keep it like that

**Review by JustaSqu1d — APPROVED** [review]

**Review by Lulalaby — APPROVED** [review]

**Pull request merged**
