### PR TITLE
Add a native timeout for modal.py

### PR DESCRIPTION
**Pull request by EEKIM10**
## Summary

Modals do not currently have a native timeout (like Views do), meaning they never leave the modal store unless the form is submitted (resulting in them being in there forever when dismissed). This PR copies and slightly modifies the same behaviour and functions from discord.ui.View, and reflects it into discord.ui.Modal.

## Checklist

- [x] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [x] If `type: ignore` comments were used, a comment is also left explaining why
- [x] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting, examples, ...)

### CODE REVIEW

**Comment by Mihitoko** [comment]
I cant for your fork since i already have a for of pycord. I cant write to your fork unfortunaly.

change line 49 to
```py
self.timeout: float = timeout
```
and line 103 to:
```
self.loop.create_task(self.on_timeout(), name=f"discord-ui-view-timeout-{self._title}")
```
This should do the trick

**Comment by EEKIM10** [comment]
I’ll make the changes when I get home tomorrow 👍

**Comment by EEKIM10** [comment]
Okay so with [ecd8d60](https://github.com/Pycord-Development/pycord/pull/1434/commits/ecd8d60b8ddde6594fd297ca3e23d88dbf05ac58), the errors are no-longer present.
However, for some reason, as soon as I init my test model, the timeout immediately starts. Looking at `interaction.response.send_modal`, it looks like it should only be added to the modal store when the modal is sent, however it seems to be starting off the timeout as soon as init() is called. I'm gonna dig through the rest of the code to see what's going on, but I must admit, the timeout system is rather funky to look at lol

**Comment by EEKIM10** [comment]
I retract my previous comment, I think I'm just being a little bit dense, I'm gonna try with some different timeouts. If I am just being dense then this PR is ready to go.

**Comment by EEKIM10** [comment]
Can confirm that this now works and has been tested. No more errors in console, and debugging seems to match up with expected results. I'm gonna open this PR for review now :)

**Comment by Mihitoko** [comment]
👍

**Comment by EmreTech** [comment]
> I cant fork your fork since i already have a fork of pycord. I cant write to your fork unfortunaly.
> 
> change line 49 to
> 
> ```python
> self.timeout: float = timeout
> ```
> 
> and line 103 to:
> 
> ```
> self.loop.create_task(self.on_timeout(), name=f"discord-ui-view-timeout-{self._title}")
> ```
> 
> This should do the trick

FYI, you could've just reviewed this PR and included suggestions.

**Review by EmreTech — APPROVED** [review]
Haven't tested, but the code portions look good

**Review by Lulalaby — APPROVED** [review]

**Review by Dorukyum — APPROVED** [review]

**Pull request merged**
