### PR TITLE
Voice Receiving 

### PR DESCRIPTION
**Pull request by VincentRPS**
## Summary

Voice Recording Stabilizing & Building Off Of https://github.com/Rapptz/discord.py/pull/6507

## Checklist

- [x] Stabilize
   - I Would Call it Stable In It's Current State
- [x] Finish The TODO's
- ~~Possibly Rename Sink~~
   - Decided it didn't need to be.
- [x] Test With A lot of people (~10)

### Bugs

- ~~When 2 People Talk There Is Static~~
    - Fixed

## Checklist

- [x] This PR adds something new (e.g. new method or parameters).

### CODE REVIEW

**Comment by pgamerx** [comment]
hello

**Comment by RPSMain** [comment]
@BobDotCom if you could move this into V2.0 that would be great

**Review by CodeWithSwastik — APPROVED** [review]
I've tested it and it works perfectly. Haven't gone through the code thoroughly yet.

**Comment by CodeWithSwastik** [comment]
This can be merged when the hardcoded os stuff is removed and bytes are supported.

**Review by Swhistler1 — COMMENTED** [review]
.

**Pull request merged**
