### PR TITLE
Pre commit initiate

### LINKED ISSUE #228: Add pre-commit and github actions to encourage contributors push code aligned with PEP
### Summary

add pre-commit and github actions for  linting and auto styling 

### What is the feature request for?

The core library

### The Problem

I see that the code has significant number of issues related to python styling convention violation. As such, it would be a great idea to add [pre-commit](https://pre-commit.com) and necessary github actions so that new developers can readily use it and avoid violating python code convention.

### The Ideal Solution

Adding pre-commit and necessary github actions for the job(linting and auto-styling)

### The Current Solution

None

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by bhattbhuwan13**
## Summary

Fixes #228 

## Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [x] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] This PR is **not** a code change (e.g. documentation, README, typehinting, ...)

### CODE REVIEW

**Comment by BobDotCom** [comment]
I was thinking we could have an action that ran flake8 on pull requests, and failed the check if it didn't pass. We could then have some optional way to trigger the black formatting, maybe similar to #292 (using a label as a trigger).

**Comment by bhattbhuwan13** [comment]
> I was thinking we could have an action that ran flake8 on pull requests, and failed the check if it didn't pass. We could then have some optional way to trigger the black formatting, maybe similar to #292 (using a label as a trigger).

@BobDotCom, Actually we need to have both. Knowing that your coding style doesn't confirm to the PEP guidelines only after pushing the code to the main repo will be a hassle. Hence, I suggest that we use both. Precommit can be used by developer on his machine for the sake of comfort and the github actions will ensure that everything confirms to the coding guidelines before merging code.

**Review by FrostByte266 — COMMENTED** [review]
I for sure agree with enforcing clean code style. I am not very well versed with GH Actions, so I can't comment on the setup of it.

**Review by Dorukyum — COMMENTED** [review]
> I for sure agree with enforcing clean code style. I am not very well versed with GH Actions, so I can't comment on the setup of it.

Same for me.

**Comment by Lulalaby** [comment]
I'm gonna review it

**Comment by Lulalaby** [comment]
The github actions seems to be missing

**Comment by Lulalaby** [comment]
See https://github.com/Lulalaby/pycord/runs/4108965477?check_suite_focus=true

**Comment by Lulalaby** [comment]
@bhattbhuwan13 see https://github.com/bhattbhuwan13/pycord/pull/1

**Review by Lulalaby — CHANGES_REQUESTED** [review]
Merge workflow pr

**Comment by Lulalaby** [comment]
Stale

**Pull request closed without merging**
