### PR TITLE
Changed discord.py & discord to Pycord.

### PR DESCRIPTION
**Pull request by Neilisop**
## Summary

This pull request changes wherever there is discord or discord.py in the docs and the main __init__.py file.

## Checklist

- [x] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by Seniatical** [comment]
This wasn't created by pycord. It's a fork of a project, which means they have no right to remove original copyright. As highlighted by Danny in my previous mistakes.
image

**Comment by Neilisop** [comment]
Even though it was NOT voilating his copyright as I did not change it, I only changed where it said discord.py to pycord which is indeed allowed. I did not change his copyright, if you go and look there's still his copyright (2015-present copyright Rapptz) it clearly states `Permission is hereby granted, free of charge, to any person obtaining a
copy of this software and associated documentation files (the "Software"),
to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense,
and/or sell copies of the Software, and to permit persons to whom the
Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.`.

**Comment by Neilisop** [comment]
I've changed it in the __init__ file if you still think it's voilating.

**Comment by Seniatical** [comment]
The same goes with the docs, they can only claim it there's if:
A: They rewrite the build for sphinx
B: Use a different layout - Credits for the builder and extensions will still be required
C: Use something completely different like MKDocs

**Comment by Seniatical** [comment]
And the `__author__` and `__title__` tag point to the original creator and project so yes it is changing the license to some some extent

**Comment by namzop** [comment]
He never removed the attribution from the license or the copyright
image
And maybe he sent you that message because you changed the attribution in the LICENSE file.

**Comment by namzop** [comment]
> I've changed it in the **init** file if you still think it's voilating.

As mentioned in the message, danny said that "he'd prefer if the license and copyright was kept without removing attribution" but you never removed attribution from the license or the copyright.

**Comment by Seniatical** [comment]
> He never removed the attribution from the license or the copyright
> image
> And maybe he sent you that message because you changed the attribution in the LICENSE file.

If you checked the commit it was the `__init__`

**Pull request closed without merging**
