### PR TITLE
discord.ext.bridge

### LINKED ISSUE #451: Add support between application commands and normal commands in `commands.Bot`
A compatibility layer proposed by @BobDotCom

### PR DESCRIPTION
**Pull request by BobDotCom**
## Summary

Adds compatibility between discord.commands and ext.commands.

## Checklist

- [x] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [x] If `type: ignore` comments were used, a comment is also left explaining why
- [x] This PR fixes an issue. Fixes #451 
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting, examples, ...)

### CODE REVIEW

**Comment by plun1331** [comment]
I feel like `compat` isn't a great name for this

**Comment by krittick** [comment]
> I feel like `compat` isn't a great name for this

Same. Maybe ext.bridge or something?

**Comment by PrathamWasTaken** [comment]
.

**Review by EmreTech — APPROVED** [review]

**Review by krittick — APPROVED** [review]

**Review by Dorukyum — APPROVED** [review]
LGTM

**Pull request merged**
