### PR TITLE
fix(ext.bridge): fix groups missing parent attr

### LINKED ISSUE #1816: Attribute error for `class.BridgeCommandGroup` in `HelpComand()`
### Summary

Error raised while using `help` command:  'BridgeCommandGroup' object has no attribute 'parent' 

### Reproduction Steps

Was using a custom `discord.ext.commands.HelpCommand` earlier, however the error is raised even while using `discord.ext.commands.DefaultHelpCommand`

### Minimal Reproducible Code

```python
class AbletonBot(bridge.Bot):
    def __init__(self):
        intents = discord.Intents.all()
        intents.presences = False
        prefixlist = ["o!","O!"]
        super().__init__(
            intents=intents,
            command_prefix=commands.when_mentioned_or(*prefixlist),
            case_insensitive=True,
            enable_debug_events=True,
            strip_after_prefix=True,
            description="something...",
            help_command=commands.DefaultHelpCommand()
        )
```

### Expected Results

The bot to return the help menu. It was working fine before the bridge commands were added.

### Actual Results

image

Error:
```py
  File "G:/Development/infinix/ableton/env/lib/python3.9/site-packages/discord/ext/commands/cog.py", line 84, in get_commands
    return [c for c in self.__cog_commands__ if c.parent is None]
  File "G:/Development/infinix/ableton/env/lib/python3.9/site-packages/discord/ext/commands/cog.py", line 84, in <listcomp>
    return [c for c in self.__cog_commands__ if c.parent is None]
AttributeError: 'BridgeCommandGroup' object has no attribute 'parent'
```

### Intents

all (except `intents.presences`)

### System Information

DeprecationWarning: VersionInfo.releaselevel is deprecated since version 2.3, consider using release_level instead.
  "- py-cord v{0.major}.{0.minor}.{0.micro}-{0.releaselevel}".format(version_info)
C:\Users\Acer\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\__main__.py:49: DeprecationWarning: VersionInfo.releaselevel is deprecated since version 2.3, consider using release_level instead.
  if version_info.releaselevel != "final":
- Python v3.11.0-final
- py-cord v2.3.1-final
- aiohttp v3.8.3
- system info: Windows 10 10.0.19045

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by Middledot**
## Summary
self-explanatory
Fix #1816

<details>
<summary>Test code used</summary>

```python
class Bot(bridge.Bot):
    def __init__(self):
        intents = discord.Intents.all()
        intents.presences = False
        super().__init__(
            intents=intents,
            command_prefix="::",
            case_insensitive=True,
            enable_debug_events=True,
            strip_after_prefix=True,
            description="something...",
            help_command=commands.DefaultHelpCommand()
        )

bot = Bot()
bot.load_extension("jishaku")

class Test(commands.Cog):
    @bridge.bridge_group(invoke_without_command=False)
    async def layer(self, ctx):
        await ctx.respond("hello!!!")

    @layer.command(invoke_without_command=False)
    async def one(self, ctx):
        await ctx.respond("All systems green")

bot.add_cog(Test())
```

</details>

## Information

- [x] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed).
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting,
      examples, ...).

## Checklist

- [x] I have searched the open pull requests for duplicates.
- [x] If code changes were made then they have been tested.
  - [ ] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why.

### CODE REVIEW

**Review by Nzii3 — APPROVED** [review]

**Review by Lulalaby — DISMISSED** [review]

**Review by BobDotCom — CHANGES_REQUESTED** [review]
Please add a changelog entry

**Comment by Nzii3** [comment]
> Please add a changelog entry

Where?

**Comment by Lulalaby** [comment]
> > Please add a changelog entry
> 
> Where?

In deez nuts :3

**Comment by Lulalaby** [comment]
just kidding https://github.com/Middledot/pycord/blob/bridge-fix/CHANGELOG.md

**Comment by Nzii3** [comment]
> just kidding https://github.com/Middledot/pycord/blob/bridge-fix/CHANGELOG.md

Crap I thought this was my pr :/

**Comment by Middledot** [comment]
Apologies for the delay, the entry is added

**Review by Lulalaby — APPROVED** [review]

**Review by BobDotCom — APPROVED** [review]

**Pull request merged**
