### PR TITLE
fixing issue with not working audo_recordings example

### PR DESCRIPTION
**Pull request by TheGiga**
## Summary

I fixed an error that was caused probably by using enum, but im not sure.
My personal opinion, is that pevious example was cleaner and simply better.
Had to use dict once again, because i was too lazy to fix Enum thing, if someone wants to try fixing it using Enum - you're welcome.

I prefer using Enum aswell, because it looks cooler, but it just didn't work well here.

There is some error messages that user on pycord's discord server was getting:

image

I was able to recreate the issue by simply trying to use code from example:
image

**With updated code i got it to work**:

p9MvbK0hvd

## Information

- [x] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed).
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting, examples, ...).

## Checklist

- [ ] I have searched the open pull requests for duplicates.
- [x] If code changes were made then they have been tested.
  - [ ] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why.

### CODE REVIEW

**Review by EmreTech — APPROVED** [review]
Looks good, but you might want to change the name of this PR to sound more confident that this is the fix.

**Comment by TheGiga** [comment]
> This doesn't fix the issue with the enum, instead just removes it.

that's why im calling it possible fix, but yes, i could named it better.
At least, this works.

**Comment by Lulalaby** [comment]
I think we should fix the issue instead of removing this all

**Comment by Dorukyum** [comment]
The issue doesn't even lie in the example, rather in the library. I'll try to fix that.

**Comment by Lulalaby** [comment]
Closing as invalid. 
Fix needs to be done in library. 
@Dorukyum will look into this.

**Comment by Dorukyum** [comment]
https://github.com/Pycord-Development/pycord/commit/ef301fcaaae0810a5a38c0c856355821102526ea should fix this.

**Pull request closed without merging**
