### PR TITLE
feat: Allow users to run one command to install both packages for speedup and voice support

### PR DESCRIPTION
**Pull request by catdogmat**
## Summary

This PR allows users to run one command to install both packages for speedup and voice support, eg:
`python3 -m pip install py-cord[all]`

## Information

- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters). (kinda, it adds a new install method)
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed).
- [x] This PR is **not** a code change (e.g. documentation, README, typehinting,
      examples, ...). (kinda, it updates docs and pyproject)

## Checklist

- [x] I have searched the open pull requests for duplicates.
- [x] If code changes were made then they have been tested.
- [x] I have updated the documentation to reflect the changes.
- [x] If `type: ignore` comments were used, a comment is also left explaining why.
- [x] I have updated the changelog to include these changes.

### CODE REVIEW

**Comment by catdogmat** [comment]
Closing as I think I broke something

**Comment by catdogmat** [comment]
Ok fixed

**Comment by catdogmat** [comment]
Fixing title

**Comment by catdogmat** [comment]
Sorry if this is bad, I'm new to big repos

**Comment by Lulalaby** [comment]
Thanks for your contribution. In my opinion this isn't really needed tho.
We'll discuss that.

**Comment by Lulalaby** [comment]
We're not gonna accept this PR at this point.
Thank you tho

**Comment by VincentRPS** [comment]
Is `pycord[speed,voice]=a.b.c` just too much? I don't think there is any worth in adding a shortcut to what is already so simple. Maybe in the future, if we get more extra dependencies, but at the moment, two is not enough.

**Pull request closed without merging**
