### PR TITLE
feat: implement Avatar Decorations

### PR DESCRIPTION
**Pull request by NeloBlivion**
## Summary

Better late than never...?
There seems to be several different endpoints, so I've tried to include them.
Despite no longer being available, you can still get any user's decoration.
Unlike banners, `User.avatar_decoration` is always received without needing to fetch the user.

## Information

- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed).
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting,
      examples, ...).

## Checklist

- [x] I have searched the open pull requests for duplicates.
- [x] If code changes were made then they have been tested.
  - [x] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why.
- [x] I have updated the changelog to include these changes.

### CODE REVIEW

**Comment by Om1609** [comment]
discord/discord-api-docs#5723 got merged. This can too?

**Comment by Lulalaby** [comment]
On hold till adc rolls out

**Comment by Dorukyum** [comment]
> On hold till adc rolls out 

@Lulalaby update?

**Comment by Lulalaby** [comment]
There have been some recent changes. Imma look this week

**Comment by Lulalaby** [comment]
lets finish that up

**Comment by NeloBlivion** [comment]
Decorations haven't changed much, apart from one thing; we now recieve a dict `avatar_decoration_data` instead:
```py
{'asset': 'a_c7e1751e8122f1b475cb3006966fb28c', 'sku_id': '1154896005045694555'}
```
The asset ID is all we really need, does sku_id serve any purpose from a bot perspective? At the moment we still save that entire dict under `User._avatar_decoration`.

**Review by Dorukyum — APPROVED** [review]

**Pull request merged**
