### PR TITLE
commands.has_permissions() return True in DM channels (fix #1576)

### LINKED ISSUE #1576: commands.has_permissions() decorator dont work correctly in DM channels
### Summary

commands.has_permissions() decorator dont work correctly in DM channels

### Reproduction Steps

- Create command with @commands.has_permissions() decorator
- Try to use command in DM Channel

### Minimal Reproducible Code

```python
from discord.ext import commands
...

@commands.slash_command()
@commands.has_permissions(manage_guild=True)
async def test(self, ctx: discord.ApplicationContext:
    pass
```

### Expected Results

has_permissions should return True while using commands/slash commands in DM channel:
```If the command is executed within a DM, it returns "True".``` [(link)](https://github.com/Pycord-Development/pycord/blob/e0d4c4549a7706fd9966745e64a464a27d3da21f/discord/ext/commands/core.py#L2095)

### Actual Results

```bash
Ignoring exception in on_interaction
Traceback (most recent call last):
  File "C:\Users\*\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 382, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\*\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\bot.py", line 1043, in on_interaction
    await self.process_application_commands(interaction)
  File "C:\Users\*\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\bot.py", line 738, in process_application_commands
    await self.invoke_application_command(ctx)
  File "C:\Users\*\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\bot.py", line 994, in invoke_application_command
    await ctx.command.invoke(ctx)
  File "C:\Users\*\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\commands\core.py", line 355, in invoke
    await self.prepare(ctx)
  File "C:\Users\*\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\commands\core.py", line 277, in prepare
    if not await self.can_run(ctx):
  File "C:\Users\*\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\commands\core.py", line 374, in can_run
    return await async_all(predicate(ctx) for predicate in predicates)  # type: ignore
  File "C:\Users\*\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\utils.py", line 562, in async_all
    for elem in gen:
  File "C:\Users\*\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\commands\core.py", line 374, in <genexpr>
    return await async_all(predicate(ctx) for predicate in predicates)  # type: ignore
  File "C:\Users\*\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\ext\commands\core.py", line 2120, in predicate
    permissions = ch.permissions_for(ctx.author)  # type: ignore
AttributeError: 'PartialMessageable' object has no attribute 'permissions_for
```

### Intents

```py
discord.Intents.all()
```

### System Information

```bash
- Python v3.8.13-final
- py-cord v2.1.0-final
- aiohttp v3.8.1
- system info: Linux 5.4.0-122-generic #138-Ubuntu SMP Wed Jun 22 15:00:31 UTC 2022
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

https://discordpy.readthedocs.io/en/latest/interactions/api.html#discord.Interaction.channel

Note that due to a Discord limitation, DM channels are not resolved since there is no data to complete them. 
These are [PartialMessageable](https://discordpy.readthedocs.io/en/latest/api.html#discord.PartialMessageable) instead.

### PR DESCRIPTION
**Pull request by yoggys**
## Summary

This PR fix issue #1576 (commands.has_permissions() decorator problem with DM channels)

## Information

- [x] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed).
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting, examples, ...).

## Checklist

- [x] I have searched the open pull requests for duplicates.
- [x] If code changes were made then they have been tested.
  - [ ] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why.

### CODE REVIEW

**Comment by Lulalaby** [comment]
**I don't think that should be done!**

This could enable users to workaround guild perms in some cases.
If you rely on permissions, then don't show the commands in dms, instead, do overloads for dms.

**Comment by yoggys** [comment]
> **I don't think that should be done!**
> 
> This could enable users to workaround guild perms in some cases. If you rely on permissions, then don't show the commands in dms, instead, do overloads for dms.

Hm then https://github.com/Pycord-Development/pycord/blob/e0d4c4549a7706fd9966745e64a464a27d3da21f/discord/ext/commands/core.py#L2095 should be removed/replaced with something like https://github.com/Pycord-Development/pycord/blob/e0d4c4549a7706fd9966745e64a464a27d3da21f/discord/ext/commands/core.py#L2171

**Comment by Lulalaby** [comment]
We'll take a look onto that later

**Comment by plun1331** [comment]
> **I don't think that should be done!**
> 
> This could enable users to workaround guild perms in some cases.
> If you rely on permissions, then don't show the commands in dms, instead, do overloads for dms.

If it's not in a guild context it should be fine, as most commands using guilds are based on the guild that the command was run in.

I also think it's up to the developer to ensure that commands can't be used when they shouldn't be used, and introducing such a vulnerability would be a result of an issue with their code, not ours.

**Comment by yoggys** [comment]
> > **I don't think that should be done!**
> > This could enable users to workaround guild perms in some cases.
> > If you rely on permissions, then don't show the commands in dms, instead, do overloads for dms.
> 
> If it's not in a guild context it should be fine, as most commands using guilds are based on the guild that the command was run in.
> 
> I also think it's up to the developer to ensure that commands can't be used when they shouldn't be used, and introducing such a vulnerability would be a result of an issue with their code, not ours.

I just have a similar approach - things should be simplified, and looking at the description of the function, it should have been working as it is now in PR for several months. It's worth noting that if someone used this decorator inappropriately then they had things thrown at the console (as in #1576) whether for slash or regular commands used in DMs.

**Review by Dorukyum — APPROVED** [review]
Looks good to me

**Review by BobDotCom — APPROVED** [review]

**Pull request merged**
