### PR TITLE
Add __call__ to ApplicationCommand

### PR DESCRIPTION
**Pull request by MhmCats**
## Summary

Apparently last time I PR'd to the wrong branch :cry:. Anywho, this PR is the same as the other one. 

## Checklist

- [x] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Review by Grace-codes — APPROVED** [review]

**Comment by Dorukyum** [comment]
Apparently this will be added/merged after cogs are ready.

**Comment by CodeWithSwastik** [comment]
Seems good to me, no reason to wait for cogs.

**Comment by Grace-codes** [comment]
Would be useful to point this out but this should be added

**Comment by Dorukyum** [comment]
> no reason to wait for cogs

I was going to add this including Grace's suggestion but I was told to wait until cogs 🤔

**Pull request merged**
