### PR TITLE
Allow JSON Embeds For Easier Use

### PR DESCRIPTION
**Pull request by MananaTheOne**
this pr creates a feature

### CODE REVIEW

**Review by ChickenDevs — CHANGES_REQUESTED** [review]
A lot still needs done here for this to even be a valid PR. You need to update doc strings, and should be using `is not None` instead of `!= None`

**Comment by krittick** [comment]
This is the opposite of what a library should provide. The whole point is to make it easier than needing to pass JSON to the API directly.

**Comment by Lulalaby** [comment]
Furthermore `this pr creates a feature` is not wanted.
First, we have a pr template, don't delete it.
Second: Make yourself familiar with our CoC (https://github.com/Pycord-Development/pycord/blob/master/.github/CODE_OF_CONDUCT.md) and Contributing (https://github.com/Pycord-Development/pycord/blob/master/.github/CONTRIBUTING.md)

**Comment by MananaTheOne** [comment]
The point of why I made the PR is because there are alot of embed generators and most of them have a JSON (or dict) output, and makes it easier for some people.

**Comment by plun1331** [comment]
> The point of why I made the PR is because there are alot of embed generators and most of them have a JSON (or dict) output, and makes it easier for some people.

`Embed` has a `from_dict` method

**Pull request closed without merging**
