### PR TITLE
GitHub Action to test Python code with pytest

### LINKED ISSUE #102: AttributeError: discord.client.Client().application_flags
### Summary

AttributeError: 'ConnectionState' object has no attribute 'application_flags'

### Reproduction Steps

import discord ; discord.client.Client().application_flags

### Minimal Reproducible Code

```python
import discord ; discord.client.Client().application_flags
```

### Expected Results

flags

### Actual Results

AttributeError: 'ConnectionState' object has no attribute 'application_flags'

### Intents

None

### System Information

master branch of this repo.

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by cclauss**
## Summary

Fixes #102

Results: https://github.com/cclauss/pycord/actions

$ `pytest`
```
============================= test session starts ==============================
platform linux -- Python 3.9.6, pytest-6.2.5, py-1.10.0, pluggy-1.0.0
rootdir: /home/runner/work/pycord/pycord
plugins: asyncio-0.15.1
collected 9 items

tests/client_test.py .........                                           [100%]

============================== 9 passed in 0.54s ===============================
```

## Checklist

- [x] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [x] This PR fixes an issue.
- [x] This PR adds something new (e.g. new tests).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by cclauss** [comment]
@Dorukyum Your review please on `test_client_login_token_invalid_datatype()` which tests the changes made in #88

**Review by Dorukyum — APPROVED** [review]

**Comment by Grace-codes** [comment]
I thought someone was already working on the `unittest` branch

**Comment by cclauss** [comment]
It has been 9 daze…

**Comment by FrostByte266** [comment]
@cclauss I am the one who has been writing the unit testing framework, it is very much (as you can see) in the very early stages of development (I am using the standard library module `unittest`). Currently working on the ability to use a proxy to inspect outbound requests without actually sending them to discord. This allows one to test functionality without actually creating, updating, or deleting any resource on the discord API. If you are interested in contributing, I'd be happy to have someone else participate in the development of the framework.

**Comment by Lulalaby** [comment]
Closing as dup of `unittest`

**Pull request closed without merging**
