### PR TITLE
feat(ext.pages): Add ButtonTypes presets for paginator buttons

### PR DESCRIPTION
**Pull request by Nzii3**
## Summary

Adds a `ButtonTypes` class that allows users to use preset paginator button styles easily.

> ⚠ **THIS PR IS STILL NOT FINISHED!**

## Information

- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed).
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting,
      examples, ...).

## Checklist

- [x] I have searched the open pull requests for duplicates.
- [x] If code changes were made then they have been tested.
  - [ ] I have updated the documentation to reflect the changes.
- [x] If `type: ignore` comments were used, a comment is also left explaining why.

### CODE REVIEW

**Comment by Lulalaby** [comment]
Isn't that a dup of https://github.com/Pycord-Development/pycord/pull/1811 ?

Couldn't that be done in scope of that pr?

**Comment by EmreTech** [comment]
> Isn't that a dup of #1811 ?
> 
> Couldn't that be done in scope of that pr?

I think this PR is based on that other PR because this PR requires changes made in the other PR.

**Comment by EmreTech** [comment]
Misread, sorry.

**Comment by Nzii3** [comment]
> Isn't that a dup of #1811 ?
> 
> Couldn't that be done in scope of that pr?
@Lulalaby I think Bob wanted a separate thing but they are similar. [Context](https://discord.com/channels/881207955029110855/1048680043871735889)

**Comment by Nzii3** [comment]
I could add it into that pr tho

**Comment by BobDotCom** [comment]
status?

**Comment by Nzii3** [comment]
> status?

Sorry, not done yet. Been kinda busy with other projects. I’ll work on it this weekend.

**Comment by Nzii3** [comment]
> Could you add a way to pass in the ButtonTypes class into a classmethod constructor (or as a param in the init constructor) for the paginator? The use_styled_buttons/use_default_buttons params should also access the ButtonTypes class.

Will do.

**Comment by Nzii3** [comment]
Been busy.

**Comment by Lulalaby** [comment]
@Nzii3 shall we trash this

**Comment by Nzii3** [comment]
> @Nzii3 shall we trash this

@Lulalaby yes

**Pull request closed without merging**
