### PR TITLE
Improved example docs for audio_recording

### PR DESCRIPTION
**Pull request by UP929312**
This PR includes clean-up and better formatting, rather than using a huge if else tree it uses a dictionary which also improves integrity of options

## Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] This PR is **not** a code change (e.g. documentation, README, typehinting, examples, ...)

### CODE REVIEW

**Comment by Dorukyum** [comment]
Maybe we could use an enum option for this (ref: #1292)

**Comment by UP929312** [comment]
> Maybe we could use an enum option for this (ref: #1292)

I guess in the future that might be a decent idea, it's been about a month and a half since that branch/PR was created, so until it's finished, this is probably a good idea

**Review by Dorukyum — APPROVED** [review]
We can merge this now and update with an enum option later.

**Review by Lulalaby — APPROVED** [review]

**Review by Dorukyum — APPROVED** [review]
LGTM :)

**Review by Lulalaby — APPROVED** [review]

**Pull request merged**
