### PR TITLE
Adding `on_check_failure` to `View` class

### PR DESCRIPTION
**Pull request by Kile**
## Summary

I have submitted this pull request before but Danny ended up denying it. I still find this relevant and useful so I am submitting it here again.

This pull request adds the Coro `on_check_failure` to the `View` class which is called when `interaction_check` returns `False` and defers the interaction, if not previously responded to, per default (EDIT: it now does not defer the interaction per default anymore).

Why this is needed:
`interaction_check`'s purpose is to check if the interaction should go through, not really to handle the case of it not going through. A separate method handling what to do when the check fails seems more clean and useful to deal with that.
So thing code which would previously look like
```py
async def interaction_check(self, interaction: discord.Interaction) -> bool:
    if not some_check():
        await interaction.response.defer()
        return False
    return True
```
looks now like
```py
async def on_check_failure(self, interaction: discord.Interaction) -> None:
    await interaction.response.defer()

async def interaction_check(self, interaction: discord.Interaction) -> bool:
    return some_check():
```
## Checklist

- [ ] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting, examples, ...)

### CODE REVIEW

**Comment by plun1331** [comment]
I feel like doing this in `interaction_check` is easier, mostly because you would know what condition failed.

The feature could have it's uses though.

**Comment by krittick** [comment]
I think it would be best to just add the method itself (to allow subclassing and better code organization) but not provide a default behavior (i.e. don't auto-defer on failure).

**Comment by Kile** [comment]
I don't mind changing it to that if you'd like me to

**Review by Dorukyum — APPROVED** [review]

**Comment by plun1331** [comment]
Is anything going to happen with this for 2.0?

**Comment by krittick** [comment]
> Is anything going to happen with this for 2.0?

It's marked as a 2.1 feature and still in draft.

**Review by Lulalaby — DISMISSED** [review]

**Review by Lulalaby — APPROVED** [review]

**Review by baronkobama — APPROVED** [review]
The code looks good to me. 👍

**Review by ChickenDevs — APPROVED** [review]

**Pull request merged**
