### PR TITLE
feat: Move ctx.respond to Interaction and implement Interaction.edit

### PR DESCRIPTION
**Pull request by NeloBlivion**
## Summary

`ctx.respond` and `ctx.edit` have existed for a while now for convenient command responses, but the same can't be said for `Interaction`. This PR does the following:
- `ctx.respond` is moved to `Interaction`; the `ctx` version now simply references `self.interaction.respond`
- `Interaction.edit` is added as a shortcut for `InteractionResponse.edit_message` and `Interaction.edit_original_response`

## Information

- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed).
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting,
      examples, ...).

## Checklist

- [x] I have searched the open pull requests for duplicates.
- [x] If code changes were made then they have been tested.
  - [x] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why.
- [ ] I have updated the changelog to include these changes.

### CODE REVIEW

**Review by Lulalaby — CHANGES_REQUESTED** [review]
Changelog

**Review by Lulalaby — APPROVED** [review]

**Comment by Lulalaby** [comment]
@NeloBlivion Unsure, but could it be that this is a breaking change?

**Comment by NeloBlivion** [comment]
> @NeloBlivion Unsure, but could it be that this is a breaking change?

Fortunately not, `ctx.respond` performs the exact same. We've already used the `@property` + `copy_doc` method in some other places in the library to essentially copy the same function to other classes.

**Comment by Lulalaby** [comment]
oh interesting

**Review by Lulalaby — APPROVED** [review]

**Pull request merged**
