### PR TITLE
fix: attribute error in command serialization

### PR DESCRIPTION
**Pull request by Mihitoko**
## Summary
When Serializing commands which have a `Annotated` annotation it comes to a AttributeError because the type information is not wrapped in SlashCommand type.

## Information

- [x] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed).
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting,
      examples, ...).

## Checklist

- [x] I have searched the open pull requests for duplicates.
- [x] If code changes were made then they have been tested.
  - [x] I have updated the documentation to reflect the changes.
- [x] If `type: ignore` comments were used, a comment is also left explaining why.
- [x] I have updated the changelog to include these changes.

### CODE REVIEW

**Comment by Mihitoko** [comment]
This PR will close https://github.com/Pycord-Development/pycord/issues/2223

**Review by Dorukyum — CHANGES_REQUESTED** [review]

**Comment by Dorukyum** [comment]
I've solved the merge conflict and will approve after testing.

**Comment by Mihitoko** [comment]
> I've solved the merge conflict and will approve after testing.

Thank you

**Review by plun1331 — DISMISSED** [review]
Tested with following:
```py
import typing
import discord
from discord.ext import commands

bot = commands.Bot()

@bot.slash_command(options=[discord.Option(int, name="my-option", description="This is my option!")])
async def my_command1(ctx: discord.ApplicationContext, my_option: int):
    await ctx.respond("Hey, %d is my option!" % my_option)

@bot.slash_command()
async def my_command2(ctx: discord.ApplicationContext, my_option: discord.Option(int, name="my-option", description="This is my option!")):
    await ctx.respond("Hey, %d is my option!" % my_option)

@bot.slash_command()
async def my_command3(ctx: discord.ApplicationContext, my_option: typing.Annotated[int, discord.Option(int, name="my-option", description="This is my option!")]):
    await ctx.respond("Hey, %d is my option!" % my_option)

print(my_command1.to_dict())
print(my_command2.to_dict())
print(my_command3.to_dict())
```

**Review by plun1331 — APPROVED** [review]

**Review by Lulalaby — APPROVED** [review]

**Pull request merged**
