### PR TITLE
fix: KeyError when using method 'individual'

### PR DESCRIPTION
**Pull request by doluk**
## Summary

Resolve the origin of the variable `cmd` in `ApplicationCommandMixin.register_commands()` and fix a bug in the same method when using the sync method `individual`.

## Information

- [x] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed).
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting,
      examples, ...).

## Checklist

- [x] I have searched the open pull requests for duplicates.
- [x] If code changes were made then they have been tested.
  - [ ] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why.

The variable cmd originates from the for-loop in line 602, if the method is not "bulk". Therefore the old code throws a `KeyError`-Exception, because the key `name` doesnt't exists. `cmd` only has the keys `action`, `command` and `id`. This breaks the method `individual` for syncing commands.

### CODE REVIEW

**Comment by BobDotCom** [comment]
Can you please provide an example of code that would cause the KeyError previously?

**Comment by doluk** [comment]
Yes, I will post an example in a bit. Here is the non-code version:
- Create a discord client with slash commands
- Then execute `client.sync_commands(method='individual')`

**Comment by Middledot** [comment]
I think it would be better if the name of the command was passed into `register()` instead of keeping the cmd variable "floating" like that. Also, you should add a changelog entry

**Comment by Lulalaby** [comment]
@doluk please work on that, we want to get it finished <3

**Comment by doluk** [comment]
@Lulalaby @Middledot 
I removed the floating variables now completely and added the changelog entry as requested. 
Sorry for the delay. Life being life....

**Comment by Lulalaby** [comment]
We know, all fine

**Review by Middledot — APPROVED** [review]
Lgtm

**Review by Lulalaby — APPROVED** [review]

**Pull request merged**
