### PR TITLE
Fix extensions in discord.Bot

### PR DESCRIPTION
**Pull request by plun1331**
## Summary

Fixes: #816

Originally #817, uses a fix from #826

I searched around in the issues tab for other problems people found with this and only found #825, if there are others please let me know.

This was tested with:
- discord.Bot
    - Slash Commands
    - Slash Command Groups
    - Message & user commands
- ext.commands.Bot
    - Slash Commands
    - Slash Command Groups
    - Message & user application commands
    - Prefixed command groups
    - Prefixed commands

## Checklist

- [x] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why
- [x] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting, examples, ...)

### CODE REVIEW

**Comment by krittick** [comment]
This PR still causes the same error with reloading extensions that I mentioned in the original revert PR (#829):

 ```
File "/home/ubuntu/cbot/mj3.10/lib/python3.10/site-packages/discord/cog.py", line 816, in reload_extension
    self._remove_module_references(lib.__name__)
  File "/home/ubuntu/cbot/mj3.10/lib/python3.10/site-packages/discord/cog.py", line 614, in _remove_module_references
    if cmd.module is not None and _is_submodule(name, cmd.module):
AttributeError: 'SlashCommand' object has no attribute 'module' 
```

**Comment by plun1331** [comment]
> This PR still causes the same error with reloading extensions that I mentioned in the original revert PR (#829):
> 
>  ```
> File "/home/ubuntu/cbot/mj3.10/lib/python3.10/site-packages/discord/cog.py", line 816, in reload_extension
>     self._remove_module_references(lib.__name__)
>   File "/home/ubuntu/cbot/mj3.10/lib/python3.10/site-packages/discord/cog.py", line 614, in _remove_module_references
>     if cmd.module is not None and _is_submodule(name, cmd.module):
> AttributeError: 'SlashCommand' object has no attribute 'module' 
> ```

I wasn't experiencing this during testing, I'll look into it more tomorrow.

Do you have a code sample for reproducing?

**Comment by krittick** [comment]
> > This PR still causes the same error with reloading extensions that I mentioned in the original revert PR (#829):
> > ```
> > File "/home/ubuntu/cbot/mj3.10/lib/python3.10/site-packages/discord/cog.py", line 816, in reload_extension
> >    self._remove_module_references(lib.__name__)
> >  File "/home/ubuntu/cbot/mj3.10/lib/python3.10/site-packages/discord/cog.py", line 614, in _remove_module_references
> >    if cmd.module is not None and _is_submodule(name, cmd.module):
> > AttributeError: 'SlashCommand' object has no attribute 'module' 
> > ```
> 
> I wasn't experiencing this during testing, I'll look into it more tomorrow.
> 
> Do you have a code sample for reproducing?

Sure:


```py
import discord
from discord.commands import slash_command
from discord.ext import commands


class Temptests(commands.Cog):
    def __init__(self, bot):
        self.bot = bot

    @slash_command(name="test838")
    async def test838(self, ctx: discord.ApplicationContext):
        """Test for #838"""
        await ctx.respond("Test for #838")


def setup(bot):
    bot.add_cog(Temptests(bot))

```

Running this command causes the error:
```py
bot.reload_extension("extensions.temptests")  # or wherever the extension is located
```

**Comment by plun1331** [comment]
> ```python
> bot.reload_extension("extensions.temptests")
> ```

I can't seem to reproduce this, although I am on Python 3.9 instead of 3.10

**Comment by krittick** [comment]
> > ```python
> > bot.reload_extension("extensions.temptests")
> > ```
> 
> I can't seem to reproduce this, although I am on Python 3.9 instead of 3.10

I've tried with 3.9 as well and can reproduce the error there too.

**Comment by plun1331** [comment]
> > > ```python
> > > bot.reload_extension("extensions.temptests")
> > > ```
> > 
> > 
> > I can't seem to reproduce this, although I am on Python 3.9 instead of 3.10
> 
> I've tried with 3.9 as well and can reproduce the error there too.

Do you have a sample of the code in the bot's main file?

**Comment by Lulalaby** [comment]
⚠️ Raising prior to high

**Review by Lulalaby — APPROVED** [review]

**Comment by krittick** [comment]
I found a way to reliably reproduce the `module` error on a new bot. It just requires creating two extensions: one containing with a slash command group and a non-grouped slash command, and the other containing a prefix or slash command.

To trigger the error, just run /test838.

In addition to the error, the slash command in ext_temptests2 does not get registered at all.

Extension 1 (extensions/ext_temptests.py):

```py
import discord
from discord.commands import slash_command, SlashCommandGroup
from discord.ext import commands


class Temptests(commands.Cog):
    def __init__(self, bot):
        self.bot = bot

    gtest = SlashCommandGroup("gtest", "gtest")

    @gtest.command(name="dothing", description="gtest")
    async def gtest_dothing(self, ctx: discord.ApplicationContext):
        await ctx.respond("gtest_dothing")

    @slash_command(name="test838", guild_ids=[...])
    async def test838(self, ctx: discord.ApplicationContext):
        """Test for #838"""
        await ctx.respond("Test for #838")
        self.bot.reload_extension("extensions.ext_temptests2")


def setup(bot):
    bot.add_cog(Temptests(bot))
```


Extension 2 (extensions/ext_temptests2.py):
```py
from discord.ext import commands
from discord.commands import slash_command


class Temptests2(commands.Cog):
    def __init__(self, bot):
        self.bot = bot


@slash_command()
async def testing838(self, ctx):
    await ctx.respond("Test for #838")
    self.bot.reload_extension("extensions.ext_temptests")


def setup(bot):
    bot.add_cog(Temptests2(bot))
```

Main bot code:

```py
from os import listdir
from os.path import isfile, join
from discord.ext import commands
import discord
intents = discord.Intents.all()


bot = commands.Bot(command_prefix=[">", "/"], intents=intents, owner_ids=[...])
ext_list = [f for f in listdir("extensions/") if isfile(join("extensions/", f))]
extensions = [item.replace(".py", "") for item in ext_list]
for extension in extensions:
    bot.load_extension(f"extensions.{extension}")
bot.run("token here")
```

**Comment by plun1331** [comment]
> ```python
> from os import listdir
> from os.path import isfile, join
> from discord.ext import commands
> import discord
> intents = discord.Intents.all()
> 
> 
> bot = commands.Bot(command_prefix=[">", "/"], intents=intents, owner_ids=[...])
> ext_list = [f for f in listdir("extensions/") if isfile(join("extensions/", f))]
> extensions = [item.replace(".py", "") for item in ext_list]
> for extension in extensions:
>     bot.load_extension(f"extensions.{extension}")
> bot.run("token here")
> ```

The slash command in the second extension appears to have bad indentation

**Comment by krittick** [comment]
> > ```python
> > from os import listdir
> > from os.path import isfile, join
> > from discord.ext import commands
> > import discord
> > intents = discord.Intents.all()
> > 
> > 
> > bot = commands.Bot(command_prefix=[">", "/"], intents=intents, owner_ids=[...])
> > ext_list = [f for f in listdir("extensions/") if isfile(join("extensions/", f))]
> > extensions = [item.replace(".py", "") for item in ext_list]
> > for extension in extensions:
> >     bot.load_extension(f"extensions.{extension}")
> > bot.run("token here")
> > ```
> 
> The slash command in the second extension appears to have bad indentation

Good catch, updated to clarify that command registration isn't affected. The `module` AttributeError still occurs though.

**Comment by plun1331** [comment]
> > > ```python
> > > from os import listdir
> > > from os.path import isfile, join
> > > from discord.ext import commands
> > > import discord
> > > intents = discord.Intents.all()
> > > 
> > > 
> > > bot = commands.Bot(command_prefix=[">", "/"], intents=intents, owner_ids=[...])
> > > ext_list = [f for f in listdir("extensions/") if isfile(join("extensions/", f))]
> > > extensions = [item.replace(".py", "") for item in ext_list]
> > > for extension in extensions:
> > >     bot.load_extension(f"extensions.{extension}")
> > > bot.run("token here")
> > > ```
> > 
> > 
> > The slash command in the second extension appears to have bad indentation
> 
> Good catch, updated to clarify that command registration isn't affected. The `module` AttributeError still occurs though.

I believe I fixed the module AttributeError, however I may have uncovered another issue.

When testing I was printing out `bot._application_commands` as command removal was acting up, and noticed a command with ID `None`:
```py
{
    None: <discord.commands.SlashCommand name=test838>, 
    '936472246011183114': <discord.commands.SlashCommandGroup name=gtest>, 
    '936472246011183115': <discord.commands.SlashCommand name=test838>, 
    '936472246011183116': <discord.commands.SlashCommand name=testing838>
}
```
Unsure why this happened, I don't believe it's related to my PR though. Should most likely check if this can be reproduced on master.
You can see the code I was using in https://github.com/Pycord-Development/pycord/pull/838/commits/19f9e45734364ef858e715f7145ac52d276447fd, because I accidentally committed it.

**Comment by Lulalaby** [comment]
@plun1331 state

**Comment by plun1331** [comment]
> @plun1331 state

I don't believe there are any more issues

**Review by Lulalaby — APPROVED** [review]

**Review by Dorukyum — APPROVED** [review]

**Pull request merged**
