### PR TITLE
fix: change default attribute of `SlashCommandGroup`

### LINKED ISSUE #2302: Subgroup having MISSING cog attribute
### Summary

The bot raises Attribute error when you invoke a subcommand under a subgroup under a command group

### Reproduction Steps

1. Create a command group
2. Create a subgroup under it
3. Create a command under it
4. Invoke the command

### Minimal Reproducible Code

```python
group = bot.create_group("test1")
subgroup = group.create_subgroup("test2")

@subgroup.command()
async def test3(ctx):
   ...
```

### Expected Results

Run the command

### Actual Results

Raises an error

```py
Traceback (most recent call last):
  File "d:\Personal\Documents\GitHub\Grass-bot-rewrite\.venv\Lib\site-packages\discord\commands\core.py", line 131, in wrapped
    ret = await coro(arg)
          ^^^^^^^^^^^^^^^
  File "d:\Personal\Documents\GitHub\Grass-bot-rewrite\.venv\Lib\site-packages\discord\commands\core.py", line 1365, in _invoke
    await command.invoke(ctx)
  File "d:\Personal\Documents\GitHub\Grass-bot-rewrite\.venv\Lib\site-packages\discord\commands\core.py", line 378, in invoke
    await self.prepare(ctx)
  File "d:\Personal\Documents\GitHub\Grass-bot-rewrite\.venv\Lib\site-packages\discord\commands\core.py", line 299, in prepare
    if not await self.can_run(ctx):
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Personal\Documents\GitHub\Grass-bot-rewrite\.venv\Lib\site-packages\discord\commands\core.py", line 396, in can_run
    local_check = cog._get_overridden_method(cog.cog_check)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: '_MissingSentinel' object has no attribute '_get_overridden_method'
```

### Intents

All

### System Information

- Python v3.11.5-final
- py-cord v2.4.1-final
- aiohttp v3.8.6
- system info: Windows 10 10.0.22621

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

#1594 should have fixed it but it only fixed for commands under a group but not commands under a subgroup

### PR DESCRIPTION
**Pull request by Dasupergrasskakjd**
## Summary

Fixes #2302 

## Information

- [x] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed).
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting,
      examples, ...).

## Checklist

- [x] I have searched the open pull requests for duplicates.
- [x] If code changes were made then they have been tested.
  - [ ] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why.
- [x] I have updated the changelog to include these changes.

### CODE REVIEW

**Comment by Dorukyum** [comment]
Couldn't we just replace `if self.cog is not None:` lines with `if self.cog:`?

**Comment by Lulalaby** [comment]
Also please stick to naming conventions of pull requests.
fix: #number is not enough

**Comment by Dorukyum** [comment]
I reviewed some code and decided there's no reason for the cog attribute to ever be MISSING. Would you like to modify this pull request to make that attribute default to None instead?

**Comment by Dasupergrasskakjd** [comment]
> I reviewed some code and decided there's no reason for the cog attribute to ever be MISSING. Would you like to modify this pull request to make that attribute default to None instead?

I'm also not sure about why would it be MISSING, but when I run the code described in #2302 it does raise that error

**Comment by Dasupergrasskakjd** [comment]
After adding a debug line:
```py
print(self.name, type(self.cog))
```
 into SlashCommand.invoke for the slash command `/group subgroup subcommand`, when i calls it in discord it prints `subcommand <class 'discord.utils._MissingSentinel'>`

**Comment by Dasupergrasskakjd** [comment]
> Couldn't we just replace `if self.cog is not None:` lines with `if self.cog:`?

And I found out that this doesn't fix the issue but raises a `TypeError: subcommand() missing 1 required positional arguments` if the command has required arguments

**Comment by Dorukyum** [comment]
You got me wrong, I understand that you get that error because the attribute defaults to MISSING and that's what the code is supposed to do. I just don't see the point in that anymore so I think we should replace the default MISSING value with None.

**Comment by Dasupergrasskakjd** [comment]
> I reviewed some code and decided there's no reason for the cog attribute to ever be MISSING. Would you like to modify this pull request to make that attribute default to None instead?

Seems like that would fix it

> You got me wrong, I understand that you get that error because the attribute defaults to MISSING and that's what the code is supposed to do. I just don't see the point in that anymore so I think we should replace the default MISSING value with None.

Yes sorry

**Comment by Dorukyum** [comment]
Thanks, I'll finish this up.

**Comment by Dorukyum** [comment]
I've run the code provided in the issue and the bug seems to have been fixed, merging :+1:

**Review by Dorukyum — APPROVED** [review]

**Review by Lulalaby — APPROVED** [review]
meow meow

**Pull request merged**
