### PR TITLE
Add support for Input Text and Modal components

### LINKED ISSUE #490: Add Support for Modals & Input Text in Application Commands
https://github.com/discord/discord-api-docs/pull/4143

### PR DESCRIPTION
**Pull request by krittick**
## Summary

**Note:** Pretty much done, works as expected. Might need some more work on docstrings.

**Checklist:**

- [x] Base objects/classes/enums
  - [x] Input Text
  - [x] Modals
- [x] Docstrings
  - [x] Input Text
  - [x] Modals
- [x] Examples to show usage

This adds support for input text and modal components.

Closes #490 

## Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why
- [x] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting, examples, ...)

Credit to @Chiggy-Playz for their guidance in pointing me toward re-using many of the methodologies from View/Button/Select to quickly get our implementation running.

### CODE REVIEW

**Comment by VincentRPS** [comment]
import crisis lmao

**Comment by Lulalaby** [comment]
HAHAHAHA

**Comment by Lulalaby** [comment]
We def have to squash it :p

**Comment by krittick** [comment]
This is ready for review, though probably shouldn't be merged until modals are publicly released.

**Comment by Lulalaby** [comment]
Thanks for fixing the other things too!

**Review by VincentRPS — APPROVED** [review]
works fine in my testing

**Review by Lulalaby — APPROVED** [review]

**Comment by krittick** [comment]
Remaking PR as my fork broke.

**Pull request closed without merging**
