### PR TITLE
Add limit argument to basic autocomplete

### PR DESCRIPTION
**Pull request by JonathanRJoyner**
## Summary
The basic autocomplete function removes any values which do not start with the user input string. This makes it impossible to use any other type of filtering method like checking if the user input is contained in an option or using a SQL "LIKE"  function.

## Information
I've added a boolean which allows all values to be used in case a bot developer is filtering their own values. It defaults to True so that the current implementation of the function is matched but can be changed if a developer would like.

- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed).
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting,
      examples, ...).

## Checklist

- [x] I have searched the open pull requests for duplicates.
- [x] If code changes were made then they have been tested.
- [x] I have updated the documentation to reflect the changes.
- [] If `type: ignore` comments were used, a comment is also left explaining why.

### CODE REVIEW

**Comment by NeloBlivion** [comment]
I don't think this is really necessary? As stated in the name, `basic_autocomplete` is intended for a quick autocomplete from a list. But it is not required to use; you can build your own autocomplete logic as a separate function and implement it, as demonstrated in the autocomplete examples.
https://github.com/Pycord-Development/pycord/blob/5e445b3e260ff6cebd4fdd589325e15625e22f66/examples/app_commands/slash_autocomplete.py#L109-L144

**Comment by JonathanRJoyner** [comment]
> I don't think this is really necessary? As implied by the name, `basic_autocomplete` is intended for a quick autocomplete solution without much thought being put towards it. However, it is not required to use; you can build your own autocomplete logic as a separate function and implement it, as demonstrated in the autocomplete examples.
> 
> https://github.com/Pycord-Development/pycord/blob/5e445b3e260ff6cebd4fdd589325e15625e22f66/examples/app_commands/slash_autocomplete.py#L109-L144

This is a good point. I actually had to go back and try this to figure out how I ended up on this solution.

Using the autocomplete you've shown, you can not use any data that needs to be loaded (eg querying a database, reading json, etc.). I'm not sure what the root cause of the difference is but maybe this would be a better solution to the problem than changing the `basic_autocomplete ` function.

I'll dig around some more and see if I can figure out where the hangup and if the workaround is simple enough I'll submit a different pull request for that, if you'd like  to close this one out.

**Comment by NeloBlivion** [comment]
> you can not use any data that needs to be loaded (eg querying a database, reading json

You can do this perfectly fine; I myself access json in my autocomplete to load user data to choose from. However, like all interactions it has to be completed in under 3 seconds. The Toolkit bot we use in the server [even makes a request to github](
https://github.com/Dorukyum/Toolkit/blob/main/cogs/pycord.py#L62) to download the list of examples.
You can be very creative with autocomplete, you just have to be quick with it.

**Comment by JonathanRJoyner** [comment]
Thanks for this response! The queries are quick but I've obviously not set something up correctly. Going to close this and fix my issue.

Thanks again.

**Pull request closed without merging**
