### PR TITLE
Rework extension loading

### LINKED ISSUE #946: Allow directories to be passed in load_extension
### Summary

Inbuilt feature for loading all extensions in a directory, instead of manually looping through them.

### What is the feature request for?

discord.ext.commands

### The Problem

Splitting our code into individual **cogs** or **extensions** is pretty common. So it is also common to have our **extensions** in its own separate folder. And people people end up manually looping using **os** or **globs** to do so. So i'm requesting a feature to have this inbuilt.

### The Ideal Solution

The most ideal solution would be like `bot.load_extension('directory_name')` or `bot.load_extensions(['directory_1', 'directory_2'])` which support loading multiple extensions and the directories. `bot.load_extensions(os.listdir('path'))`.

### The Current Solution

_No response_

### Additional Context

Perhaps even an **exclude** kwarg to load all extensions except the specified ones.

### PR DESCRIPTION
**Pull request by baronkobama**
## Summary

This PR allows for folders to be loaded (allows for recursing through folders as well) in `load_extension` and adds the helper method `load_extensions` that allows for loading multiple extensions in one function call. 

Closes #946

## Checklist

- [x] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting, examples, ...)

## Notes
* I've tested this PR myself and haven't found any issues but any additional testing would be much appreciated.
* Credit to @Sodynoizz for a decent portion of the code written here. Assuming this PR looks good, then it will replace #1413.

### CODE REVIEW

**Comment by Sodynoizz** [comment]
Should we change load_extensions, load_extension , reload_extension and unload_extension to asynchronous function?

**Comment by PranoyMajumdar** [comment]
> Should we change load_extensions, load_extension , reload_extension and unload_extension to asynchronous function?

No

**Comment by Sodynoizz** [comment]
> > Should we change load_extensions, load_extension , reload_extension and unload_extension to asynchronous function?
> 
> No

why?

**Comment by PranoyMajumdar** [comment]
> > > Should we change load_extensions, load_extension , reload_extension and unload_extension to asynchronous function?
> > 
> > 
> > No
> 
> why?

Because I don't like it

**Comment by krittick** [comment]
> > > > Should we change load_extensions, load_extension , reload_extension and unload_extension to asynchronous function?
> > > 
> > > 
> > > No
> > 
> > why?
> 
> Because I don't like it

Don't be a dick. Either provide a reason for your one-word comment, or don't comment at all.

**Comment by baronkobama** [comment]
PR isn't ready for merge, recursive loading doesn't appear to work currently.

**Comment by baronkobama** [comment]
Ready for review again, hopefully, bug-free this time around.

**Review by plun1331 — APPROVED** [review]
Looks good, I would suggest adding a parameter to ignore (or just print) extension loading errors if multiple extensions are being loaded, or some other solution that doesn't raise an exception and stop extensions from being loaded.

Additionally, we could consider potentially unloading loaded extensions if one fails.

**Comment by baronkobama** [comment]
> Looks good, I would suggest adding a parameter to ignore (or just print) extension loading errors if multiple extensions are being loaded, or some other solution that doesn't raise an exception and stop extensions from being loaded.

The first implementation of this idea is done in `b587b10`, please take a look when you get a chance. No parameter to change this behavior is added currently but I can add it later down the line if still recommended.

**Comment by baronkobama** [comment]
> No parameter to change this behavior is added currently but I can add it later down the line if still recommended.

This is now implemented in `9e377e7`. So far, I've extensively tested the new loading and haven't found any issues. However, due to the addition of numerous new features including a new helper function, recursive loading, and a new parameter, `store`, any additional testing would be much appreciated.

**Comment by baronkobama** [comment]
Currently mulling this over and I'm wondering about one last thing before this PR should be fully ready for review/merge: should `load_extension` be returning the isolated cog name like it currently is or should we be returning the full name that was passed? I'm not sure of this myself but I'm leaning towards returning the full name. Any feedback on this would be much appreciated.

**Comment by Lulalaby** [comment]
I would prefer full name too tbh 

@Dorukyum what you think

**Comment by Dorukyum** [comment]
> I would prefer full name too tbh
> 
> @Dorukyum what you think

I agree, it should return the full name.

**Review by Lulalaby — APPROVED** [review]

**Review by Dorukyum — APPROVED** [review]
Looks good to me

**Comment by vproyaev** [comment]
On line 856 the check is not correct, you check final_out -> it's dict in isinstance(final_out, Exception) it's wrong. Need change to isinstance(final_out[name], Exception)

**Pull request merged**
