### PR TITLE
`InteractionResponse.edit_message` in Modal Interactions

### LINKED ISSUE #1058: `interaction.response.edit_message` Does Not Work in the `discord.ui.Modal` Class
### Summary

`interaction.response.edit_message` does not work in the callback function for the `discord.ui.Modal` class.

### Reproduction Steps

1. Clone the latest version of Pycord from GitHub.
2. Use the code below.

### Minimal Reproducible Code

```python
import discord
 
from discord.ext import commands
from discord.ui import InputText, Modal, View, Button
 
bot = commands.Bot(command_prefix='!')
 
class MyModal(Modal):
    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        self.add_item(InputText(label="Short Input", placeholder="Placeholder Test"))
 
        self.add_item(
            InputText(
                label="Longer Input",
                value="Longer Value\nSuper Long Value",
                style=discord.InputTextStyle.long,
            )
        )
 
    async def callback(self, interaction: discord.Interaction):
        embed = discord.Embed(title="Your Modal Results", color=discord.Color.random())
        embed.add_field(name="First Input", value=self.children[0].value, inline=False)
        embed.add_field(name="Second Input", value=self.children[1].value, inline=False)
        await interaction.response.edit_message(embeds=[embed])
 
@bot.slash_command(name='modaltest', guild_ids=[...])
async def modaltest(ctx):
    button = Button(label="Open Modal")
    async def callback(interaction):
        modal = MyModal(title="Modal")
        await interaction.response.send_modal(modal)
    button.callback = callback
    await ctx.respond("Hello", view=View(button))
 
bot.run('token')
```

### Expected Results

The original message should be edited.

### Actual Results

[This](https://media.discordapp.net/attachments/881309521610412082/944601730220445706/unknown.png) is the error that comes in the modal window and the message is not edited.

### Intents

None

### System Information

Windows 11
Python 3.10
Pycord Master Branch (on GitHub)

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by Pysics**
## Summary

Fix #1058 

## Checklist

- [x] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting, examples, ...)

### CODE REVIEW

**Review by krittick — APPROVED** [review]
Great catch!

**Comment by EmreTech** [comment]
I would recommend changing the title & description of this PR so people can get a rough idea of what this PR is for.

**Comment by Pysics** [comment]
> I would recommend changing the title & description of this PR so people can get a rough idea of what this PR is for.

Is it fine now?

**Review by EmreTech — APPROVED** [review]
LGTM

**Comment by EmreTech** [comment]
> > I would recommend changing the title & description of this PR so people can get a rough idea of what this PR is for.
> 
> Is it fine now?

Yup.

**Review by Dorukyum — APPROVED** [review]

**Comment by Pysics** [comment]
Can someone merge this?

**Pull request merged**
