### PR TITLE
chore(python)!: remove support for python 3.8

### PR DESCRIPTION
**Pull request by Lulalaby**
Needed for new docs + python 3.8 is gonna be EOL by october
Next pycord version should be probably 3.x.x

### CODE REVIEW

**Comment by Icebluewolf** [comment]
I think the changelog could be a bit more clear and "urgent". We are removing a version of Python after all.

**Comment by Lulalaby** [comment]
Give me an example 😆

**Comment by Lulalaby** [comment]
I think that might work

**Comment by Icebluewolf** [comment]
I saw you changed it a bit but I would also add 
`⚠️ **This Version Removes Support For Python 3.8** ⚠️`
Right after
> These changes are available on the `master` branch, but have not yet been released.

**Comment by Lulalaby** [comment]
Yeah the final warning will be more visible anyways in future
But imma add it for now

**Comment by Lulalaby** [comment]
Thanks

**Pull request merged**
