### PR TITLE
Add `command.id` & Make `bot.application_commands` a list

### PR DESCRIPTION
**Pull request by Dorukyum**
## Summary
This adds an `id` attribute to application commands.
Also makes `bot.application_commands` a list.

## Checklist
- [x] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [x] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting, examples, ...)

### CODE REVIEW

**Review by Lulalaby — APPROVED** [review]

**Comment by zeffo** [comment]
IMO keeping bot.application_commands might be better since using a list could potentially affect bots with a large amount of commands

**Comment by CodeWithSwastik** [comment]
> IMO keeping bot.application_commands might be better since using a list could potentially affect bots with a large amount of commands

Agreed and I don't think there is a reason for using a list anyway.

**Comment by Dorukyum** [comment]
The dict was `{id: command}`. Now that command has the id attribute, there is no reason to keep it a dict.

**Comment by CodeWithSwastik** [comment]
> The dict was `{id: command}`. Now that command has the id attribute, there is no reason to keep it a dict.

There is, hashmap lookups are faster than looping through a list for bots with a lot of application commands.

**Comment by Dorukyum** [comment]
> > The dict was `{id: command}`. Now that command has the id attribute, there is no reason to keep it a dict.
> 
> 
> 
> There is, hashmap lookups are faster than looping through a list for bots with a lot of application commands. 

I see, but
- Application Commands
 - have limits
 - kept in dict
- ext-commands
 - dont have limits
 - kept in list

**Comment by zeffo** [comment]
Correct me if I'm mistaken, but it looks to me like ext-commands uses a dict too; they are in [GroupMixin.all_commands](https://github.com/Pycord-Development/pycord/blob/8948a52454b3c57589cd69ec46b31781594a25e9/discord/ext/commands/core.py#L116).

**Comment by Dorukyum** [comment]
It looks like that's name to command mapping, application commands were str(id) to command so I think we should keep it consistent and make that name to command.

**Comment by nerdguyahmad** [comment]
Making this a list seems okay to me because other similar properties like `Client.users`, `Client.guilds` also returns list and they have been made that way intentionally (If we take a look at the source). Besides, `Bot.get_application_command` exists for faster lookup.

**Comment by zeffo** [comment]
I think it's possible to have different commands with the same name right? EG: 1 guild command called x and 1 global command called x. The User might have two different callbacks for those functions, and we'd need to store id to command

**Comment by CodeWithSwastik** [comment]
> I think it's possible to have different commands with the same name right? EG: 1 guild command called x and 1 global command called x. The User might have two different callbacks for those functions, and we'd need to store id to command

Also the API only sends the id so it doesn't make sense to use the command name

**Comment by Dorukyum** [comment]
Alright then, I'll just revert the last commit.

**Comment by Lulalaby** [comment]
> Also the API only sends the id so it doesn't make sense to use the command name

Correct

**Comment by Dorukyum** [comment]
I am closing this pr as Swas pushed `command.id` **9 hours** after I submitted this.

**Pull request closed without merging**
