### PR TITLE
Python bytes, not Bytes just like the line above

### PR DESCRIPTION
**Pull request by cclauss**
## Summary

https://docs.python.org/3/library/stdtypes.html#bytes
https://docs.python.org/3/library/stdtypes.html#binary-sequence-types-bytes-bytearray-memoryview

## Checklist

- [x] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [x] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Review by jgayfer — COMMENTED** [review]
This looks like a lot of copy paste. For example, we don't have tests for pytest to execute.

**Comment by CodeWithSwastik** [comment]
@FrostByte266 is already setting unittests and CI up.

**Review by jgayfer — APPROVED** [review]

**Comment by cclauss** [comment]
@grace-codes Your review, please.

**Review by Grace-codes — APPROVED** [review]

**Comment by cclauss** [comment]
@CodeWithSwastik Your review, please.

**Pull request merged**
