### PR TITLE
added `disable_all_items` in `View`

### PR DESCRIPTION
**Pull request by 27Saumya**
# Warning: We have a feature freeze till release
That means we won't accept new features for now. Only bug fixes.

## Checklist

- [x] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting, examples, ...)

### CODE REVIEW

**Comment by krittick** [comment]
This still includes the get_all_members code. Please re-submit from a branch in your fork that only contains the disable_all_items code changes.

**Comment by krittick** [comment]
Actually, since this is on a separate branch anyway, just update the code to remove the get_all_members changes. Re-opened.

**Comment by Kile** [comment]
For the disable_all_members this seems pretty useless to me. I've though about something similar but it's so easy to implement yourself that a method for it seems a bit unnecessary.

Now for the include_bots parameter also added here but not mentioned, why is that needed?

**Comment by 27Saumya** [comment]
So @krittick shall i make it or not??

**Comment by 27Saumya** [comment]
Ya @Kile idk much about PRs.. so I by mistakenly created all in one branch
So that. commits came too and for the include_bots.. that PR is gonna be added ig in v2.1

**Comment by 27Saumya** [comment]
ye @UP929312 thanks i am gonna close this PR.. cuz it has older commits too.. I will rename it to exclusions

**Pull request closed without merging**
