### PR TITLE
fix: properly type ApplicationContext.author

### PR DESCRIPTION
**Pull request by CamelGamer123**
Updated `author` property of `ApplicationContext` to include typehinting for applicable types.

## Summary

This change is intended to assist IDEs like pyCharm in both creating applicable warnings and code completion. This is done to fix The reason that I am trying to add typehinting is without it pycharm kinda just doesn't recognize that the author is an instance of Member or User and throws all kinds of errors when I add proper documentation.

Documentation example:
    """
    The trade command for the bot. Allows users to trade with other users.

    Args:
        ctx (ApplicationContext): The context of the command
        user (User): The user to trade with
        item (int): The item to trade
        amount (int): The amount of the item to trade
        cost (int): The payment for the trade
    """

Without this change pycharm does not recognize that the author is an instance of Member or User. 

## Information

- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed).
- [X] This PR is **not** a code change (e.g. documentation, README, typehinting,
      examples, ...).

## Checklist

- [X] I have searched the open pull requests for duplicates.
- [ ] If code changes were made then they have been tested.
  - [ ] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why.
- [ ] I have updated the changelog to include these changes.

### CODE REVIEW

**Review by plun1331 — DISMISSED** [review]
Please add a changelog entry

**Comment by CamelGamer123** [comment]
> Please add a changelog entry 

Would it go in added, changed, or fixed?

**Comment by plun1331** [comment]
> > Please add a changelog entry 
> 
> Would it go in added, changed, or fixed?

I would say fixed since it's fixing bad typing, possibly added since there was no typehint to begin with

**Comment by JustaSqu1d** [comment]
> > > Please add a changelog entry 
> > 
> > Would it go in added, changed, or fixed?
> 
> I would say fixed since it's fixing bad typing, possibly added since there was no typehint to begin with 

In my opinion, it makes to most sense for "fixed," as well.

**Comment by CamelGamer123** [comment]
I'm assuming something along the lines of 

- Fixed type-hinting of `author` property of `ApplicationContext` to include typehinting of `User` or `Member`.
  ([#2148](https://github.com/Pycord-Development/pycord/pull/2148))

would be fine?

**Comment by Lulalaby** [comment]
Yes perfectly fine

**Comment by CamelGamer123** [comment]
I believe I have added the changelog entry correctly.

**Review by Lulalaby — APPROVED** [review]

**Pull request merged**
