### PR TITLE
fix: #1674

### LINKED ISSUE #1674: send(suppress=True) causes TypeError: Type is not JSON serializable: flag_value
### Summary

I upgraded to v2.2.1 and edited my code to use .send(suppress=True) instead of a combo of send & edit(suppress=True). Such change prompted the exception described in the title. I think addition of suppress to sending isn't working correctly.

### Reproduction Steps

1. Get a channel (in my case it's a thread, but I doubt that would be much different?)
2. Have a working code as follows:
    ```python
    message = await channel.send(content='blah blah https://junior.guru/handbook/cv/')
    await message.edit(suppress=True)
    ```
3. Upgrade to v2.2.1 or v2.2.2 (doesn't matter) and rewrite code to following:
    ```python
    await channel.send(content='blah blah https://junior.guru/handbook/cv/', suppress=True)
    ```
4. Get this exception:
    ```
    ...
        await thread.send(content=content, suppress=True)
    File "/Users/honza/Library/Caches/pypoetry/virtualenvs/juniorguru-Lgaxwd2n-py3.10/lib/python3.10/site-packages/discord/abc.py", line 1580, in send
        data = await state.http.send_message(
    File "/Users/honza/Library/Caches/pypoetry/virtualenvs/juniorguru-Lgaxwd2n-py3.10/lib/python3.10/site-packages/discord/http.py", line 240, in request
        kwargs["data"] = utils._to_json(kwargs.pop("json"))
    File "/Users/honza/Library/Caches/pypoetry/virtualenvs/juniorguru-Lgaxwd2n-py3.10/lib/python3.10/site-packages/discord/utils.py", line 599, in _to_json
        return orjson.dumps(obj).decode("utf-8")
    TypeError: Type is not JSON serializable: flag_value
    ```

### Minimal Reproducible Code

```python
See reproduction steps.
```

### Expected Results

The code works in the same way as the combo of sending & editing with the suppress keyword argument, saving one API call on its way.

### Actual Results

Code crashes.

### Intents

guilds, members, message_content

### System Information

- Python v3.10.6-final
- py-cord v2.2.2-final
- aiohttp v3.8.3
- system info: Darwin 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:20:05 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T8101

(but getting the same error on CI with Linux)

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by plun1331**
## Summary

Fixes #1674

## Information

- [x] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed).
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting,
      examples, ...).

## Checklist

- [ ] I have searched the open pull requests for duplicates.
- [x] If code changes were made then they have been tested.
  - [ ] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why.

### CODE REVIEW

**Review by Lulalaby — APPROVED** [review]
I guess you're doing it right but just for my own mind:
In c# if i have an object which can be null, x.value could fail, is it not like that in python?

**Comment by plun1331** [comment]
> I guess you're doing it right but just for my own mind: In c# if i have an object which can be null, x.value could fail, is it not like that in python?

the message flags should never be none in this scenario as they're defined like so:
```py
flags = MessageFlags.suppress_embeds if suppress else MessageFlags.DEFAULT_VALUE
```

**Review by Dorukyum — APPROVED** [review]

**Comment by Lulalaby** [comment]
I see thx

**Comment by honzajavorek** [comment]
Awesome!

**Pull request merged**
