### PR TITLE
Fix AttributeError

### PR DESCRIPTION
**Pull request by PythonIntermediateCoder**
# Warning: We have a feature freeze till release
That means we won't accept new features for now. Only bug fixes.

## Summary
Solution for `AttributeError: NoneType object has no attribute 'id'` for `Bot.sync_commands`

## Checklist

- [x] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why
- [x] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting, examples, ...)

### CODE REVIEW

**Comment by EmreTech** [comment]
I would still consider this a code change even though it's so minor

**Comment by PythonIntermediateCoder** [comment]
It's not a major change, It does not count as a major code change though, I don't need to un-mark it

**Comment by plun1331** [comment]
> It's not a major change, It does not count as a major code change though, I don't need to un-mark it

It changes the code, therefore it is a code change.

There's another box for this:
> If code changes were made then they have been tested.

**Comment by PythonIntermediateCoder** [comment]
There was something that I messed up with. Everything is going well now

**Review by ConchDev — APPROVED** [review]
Looks good.

**Review by Lulalaby — APPROVED** [review]

**Pull request merged**
