### PR TITLE
Inheritance issues

### PR DESCRIPTION
**Pull request by BobDotCom**
## Summary

Fixes a few issues with how classes inherit from each other, and improves typing for those objects. These changes *should* be solely internal and not affect usage.

## Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting, examples, ...)

### CODE REVIEW

**Comment by Dorukyum** [comment]
Is this pull request done?

**Comment by BobDotCom** [comment]
> Is this pull request done?
I was going to try to get a bit more done on it

**Comment by BobDotCom** [comment]
Got busy, but this should be fine to merge as-is

**Review by Dorukyum — APPROVED** [review]
Seems fine to me

**Review by Lulalaby — APPROVED** [review]

**Pull request merged**
