### PR TITLE
Include Japanese ReadMe file

### PR DESCRIPTION
**Pull request by pgamerx**
## Summary

This just adds ReadMe file's Japanese version in MANIFEST.json
I don't know if this will break anything or not or if this is even necessary/needed. So you all decide it yourselv

### CODE REVIEW

**Comment by iTzNao** [comment]
Please dont re upload my work, I uploaded mine first, please delete this

https://github.com/Pycord-Development/pycord/pull/150#issue-992594352

- Thanks, Nao

**Comment by nerdguyahmad** [comment]
> Please dont re upload my work, I uploaded mine first, please delete this
> 
> [#150 (comment)](https://github.com/Pycord-Development/pycord/pull/150#issue-992594352)
> 
> * Thanks, Nao

That PR doesn't has anything to do with MANIFEST.in

**Comment by iTzNao** [comment]
> > Please dont re upload my work, I uploaded mine first, please delete this
> > [#150 (comment)](https://github.com/Pycord-Development/pycord/pull/150#issue-992594352)
> > 
> > * Thanks, Nao
> 
> Your PR doesn't has anything to do with MANIFEST.in

Ah shit, the other one does lol, sorry about this one. My bad

**Comment by pgamerxdev** [comment]
> > Please dont re upload my work, I uploaded mine first, please delete this
> > [#150 (comment)](https://github.com/Pycord-Development/pycord/pull/150#issue-992594352)
> > 
> > * Thanks, Nao
> 
> Your PR doesn't has anything to do with MANIFEST.in

That's what I am saying smhh

**Comment by pgamerxdev** [comment]
@iTzNao If you don't mind, please remove your thumbs down sign which exists for no reason?

**Comment by Grace-codes** [comment]
Including the Japanese readme in the MANIFEST.in does nothing 🤦 

Just including it in the manifest doesn't make it magically appear in PyPi. You should look into what something does before PRing.

**Comment by Lulalaby** [comment]
Invalid PR

**Pull request closed without merging**
