### PR TITLE
Remove unnecessary instance check in autocomplete

### LINKED ISSUE #1630: Autocomplete does not work for slash commands in groups
### Summary

Autocomplete methods are not executed for slash commands that are under a SlashCommandGroup.

### Reproduction Steps

I created a slash command group, and added commands with autocomplete to the group. The commands would be registered successfully, but autocomplete would not work.

### Minimal Reproducible Code

```python
import discord
import environment

bot = discord.Bot()

class CustomCog(discord.Cog):

	group = discord.SlashCommandGroup(name="test")

	async def autocomplete(ctx):
		return ["hello world"]

	@group.command()
	async def random_subcommand(self, ctx, random: discord.Option(str, name="random", autocomplete=autocomplete)):
		await ctx.respond(random)

bot.add_cog(CustomCog(bot))
bot.run(environment.DISCORD_TOKEN)
```

### Expected Results

When running the bot and typing the `/test random_subcommand` command, the text `hello world` should be suggested.

### Actual Results

The `autocomplete` method in my code did not run, and no results were suggested. Discord showed an error after a couple of seconds: "Loading options failed".

### Intents

Intents.default()

### System Information

- Python v3.9.6-final
- py-cord v2.1.3-final
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19044

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

Using a debugger I narrowed it down to [this line](https://github.com/Pycord-Development/pycord/blob/master/discord/bot.py#L759), where the `command` variable is a `SlashCommandGroup`, not a `SlashCommand`. I would have submitted a PR but I saw that line was introduced in 2.1.2 (e321fa3e2a07eb869a03de3b020f09c6d8ca431c) and assume that simply removing it (which does fix the issue) will undo whatever fixes were made with that change.

# Temporary Fix

My bots weren't experiencing any of the bugs that were fixed in v2.1.2+, so reverting to **v2.1.1** works as a temporary fix for me. But your mileage may vary.

### PR DESCRIPTION
**Pull request by DefiDebauchery**
## Summary

Fixes #1630 

The autocomplete hooks recently had typechecking applied, which would only pass if a command was specifically a `Command`. Currently, sub-commands are an instance of `SlashCommandGroup`. Because of this, the check would fail, and autocomplete Options in subcommands would fail to execute. 

Note that `ApplicationCommand` also encompasses Bridged commands and Context (Message/User) commands. I'm happy to update this PR to change typechecking for `(Command, SlashCommandGroup)` if needed, but this is better than having subcommand autocomplete being broken.

## Information

- [X] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed).
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting, examples, ...).

## Checklist

- [X] I have searched the open pull requests for duplicates.
- [X] If code changes were made then they have been tested.
  - [ ] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why.

### CODE REVIEW

**Review by Lulalaby — APPROVED** [review]

**Comment by Dorukyum** [comment]
Maybe we should instead prevent SlashCommandGroups from being passed here

**Comment by Lulalaby** [comment]
> Maybe we should instead prevent SlashCommandGroups from being passed here

Would be another good approach
@DefiDebauchery what you think

**Comment by DefiDebauchery** [comment]
I suppose that depends on whether subcommands are intended to be `SlashCommandGroup`s as they currently are. IIRC there's some limitation about being able to pull subcommands out into a unique Command (but I could be way off here)

But the issue, at least for me, is that autocomplete in subcommands are completely broken in the currently-published version of Pycord. This PR essentially just reverts the typecheck change that happened in this version

**Comment by Dorukyum** [comment]
Subcommands are SlashCommand objects, they are just stored in `SlashCommandGroup.subcommands`

I think, while we're at it, we should fix the issue from the root

**Comment by DefiDebauchery** [comment]
Of course. No argument about fixing issues at a fundamental level.

However, I don't think other users of subcommands should be left out of a working version while that takes place. It's currently broken in production.

**Comment by Lulalaby** [comment]
@Dorukyum please lets merge this as temporary fix
@BobDotCom please make a rc of that

**Review by Dorukyum — APPROVED** [review]

**Pull request merged**
