### PR TITLE
Improve sticker creation checks

### LINKED ISSUE #1540: ctx.guild.create_sticker yields 400 bad request when optional parameter description is not used.
### Summary

Pycord docs mention that parameter description is  optional, however not using it in the parameters yields 400 bad request response. 

### Reproduction Steps

create a bot command using the ctx: commands.Context parameters

```py
@bot.command(name="test", description="Admin only")
async def test(ctx: commands.Context):
    file = discord.File("userelo.png")
    await ctx.guild.create_sticker(name="dada", emoji="skull", file=file)
    await ctx.respond("created")
```

Once user invokes the command /test

Error log will show :
```py
Ignoring exception in command test:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/discord/commands/core.py", line 127, in wrapped
    ret = await coro(arg)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/discord/commands/core.py", line 881, in _invoke
    await self.callback(ctx, **kwargs)
  File "/Users/andykilgore/PycharmProjects/CODStats/Bot.py", line 1770, in test
    await ctx.guild.create_sticker(name="dada", emoji="skull", file=file)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/discord/guild.py", line 2476, in create_sticker
    data = await self._state.http.create_guild_sticker(self.id, payload, file, reason)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/discord/http.py", line 360, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 0): The browser (or proxy) sent a request that this server could not understand.
```

### Minimal Reproducible Code

```python
@bot.command(name="test", description="Admin only")
async def test(ctx: commands.Context):
    file = discord.File("userelo.png")
    await ctx.guild.create_sticker(name="dada", emoji="skull", file=file)
    await ctx.respond("created")
```

### Expected Results

Since description is an optional parameter in the docs,

 1. It should not be required when invoking the ctx.guild.create_sticker function. Not including description should not raise an error and should instead create the sticker. 
 
 OR 
 
 2. docs should be updated to specify description is an required parameter. 

### Actual Results

If description is not included in the parameters, function responds with the following error message:

image

### Intents

intents = discord.Intents.default() intents.members = True intents = discord.Intents().all()

### System Information

Python : 3.9
Mac OS Ventura PB 1 

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

await ctx.guild.create_sticker(name="dada", description="test", emoji="skull", file=file)

this works fine but like I stated, description should be optional according to https://docs.pycord.dev/en/master/api.html?highlight=sticker#discord.Guild.create_sticker

Thanks!

### PR DESCRIPTION
**Pull request by Middledot**
## Summary
Fix #1540 

## Information

- [x] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed).
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting, examples, ...).

## Checklist

- [x] I have searched the open pull requests for duplicates.
- [x] If code changes were made then they have been tested.
  - [x] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why.

### CODE REVIEW

**Comment by Lulalaby** [comment]
But description is optional..

**Comment by Middledot** [comment]
Corrected, misread the docs

**Review by Lulalaby — DISMISSED** [review]
lgtm

**Review by Lulalaby — APPROVED** [review]
oh the doc string xD

**Review by ChickenDevs — APPROVED** [review]

**Comment by kilgoreandy** [comment]
TYVM!

**Pull request merged**
