### PR TITLE
Rewrite options

### PR DESCRIPTION
**Pull request by Dorukyum**
## Summary
This modifies methods of slash commands related to option parsing and validation in order to optimize them and fix as many issues as possible.
Also allows a new design for creating options:
```py
async def command(
    ctx,
    parameter: type = Option(**other_values),
)
```

## Checklist
- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [x] If `type: ignore` comments were used, a comment is also left explaining why
- [x] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [x] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting, examples, ...)

### CODE REVIEW

**Comment by EmreTech** [comment]
...Are you kidding me? I already have a PR that accomplishes the same thing

**Comment by EmreTech** [comment]
> Emre calm down!

I am trying to be calm, but the problem is I already have a PR open that also rewrites Options to have the same syntax

**Comment by Dorukyum** [comment]
The other pull request has unnecessary changes and this will fix many other problems too.

**Comment by EmreTech** [comment]
> The other pull request has unnecessary changes and this will fix many other problems too.

Then make a review about the "unnecessary changes"? Like it's not that hard

**Comment by Lulalaby** [comment]
Clone might have his reasons for doing it himself.
If you want an explanation, maybe write him a dm.
But please no discussion within a PR which could lead to public drama.

**Comment by Lulalaby** [comment]
Thank you clone ❤️

**Review by BobDotCom — APPROVED** [review]

**Review by Lulalaby — DISMISSED** [review]

**Comment by Dorukyum** [comment]
Status: trying to solve a bug caused by the value of the cog atrribute of ext.bridge commands changing

**Comment by krittick** [comment]
Getting an error when using either of the following two methods to define an option:

```py
@slash_command(name="opt_test")
async def opt_test(ctx: discord.ApplicationContext, test_option: Option(str, "Test")):
    await ctx.respond("test")

@slash_command(name="opt_test")
async def opt_test(ctx: discord.ApplicationContext, test_option: str = Option(description="Test")):
    await ctx.respond("test")
```

```
Traceback (most recent call last):
  File "C:\Users\ben\PycharmProjects\BasicBot\bot.py", line 48, in <module>
    async def opt_test(ctx: discord.ApplicationContext, test_option: Option(str, "Test")):
  File "C:\Users\ben\PycharmProjects\BasicBot\venv\lib\site-packages\discord\commands\core.py", line 1560, in decorator
    return cls(func, **attrs)
  File "C:\Users\ben\PycharmProjects\BasicBot\venv\lib\site-packages\discord\commands\core.py", line 637, in __init__
    self.options: List[Option] = self._parse_options(params)
  File "C:\Users\ben\PycharmProjects\BasicBot\venv\lib\site-packages\discord\commands\core.py", line 690, in _parse_options
    option = Option(option, "No description provided")
  File "C:\Users\ben\PycharmProjects\BasicBot\venv\lib\site-packages\discord\commands\options.py", line 133, in __init__
    _type = SlashCommandOptionType.from_datatype(input_type)
  File "C:\Users\ben\PycharmProjects\BasicBot\venv\lib\site-packages\discord\enums.py", line 670, in from_datatype
    if datatype.__name__ in ["Member", "User"]:
AttributeError: 'str' object has no attribute '__name__'. Did you mean: '__ne__'?
```

**Comment by EmreTech** [comment]
> Getting an error when using either of the following two methods to define an option:
> 
> ```python
> @slash_command(name="opt_test")
> async def opt_test(ctx: discord.ApplicationContext, test_option: Option(str, "Test")):
>     await ctx.respond("test")
> 
> @slash_command(name="opt_test")
> async def opt_test(ctx: discord.ApplicationContext, test_option: str = Option(description="Test")):
>     await ctx.respond("test")
> ```
> 
> ```
> Traceback (most recent call last):
>   File "C:\Users\ben\PycharmProjects\BasicBot\bot.py", line 48, in <module>
>     async def opt_test(ctx: discord.ApplicationContext, test_option: Option(str, "Test")):
>   File "C:\Users\ben\PycharmProjects\BasicBot\venv\lib\site-packages\discord\commands\core.py", line 1560, in decorator
>     return cls(func, **attrs)
>   File "C:\Users\ben\PycharmProjects\BasicBot\venv\lib\site-packages\discord\commands\core.py", line 637, in __init__
>     self.options: List[Option] = self._parse_options(params)
>   File "C:\Users\ben\PycharmProjects\BasicBot\venv\lib\site-packages\discord\commands\core.py", line 690, in _parse_options
>     option = Option(option, "No description provided")
>   File "C:\Users\ben\PycharmProjects\BasicBot\venv\lib\site-packages\discord\commands\options.py", line 133, in __init__
>     _type = SlashCommandOptionType.from_datatype(input_type)
>   File "C:\Users\ben\PycharmProjects\BasicBot\venv\lib\site-packages\discord\enums.py", line 670, in from_datatype
>     if datatype.__name__ in ["Member", "User"]:
> AttributeError: 'str' object has no attribute '__name__'. Did you mean: '__ne__'?
> ```

Are you including `from future import __annotations`?

**Review by EmreTech — APPROVED** [review]
Looks good, I think someone should test it with the `options` decorator.

**Comment by krittick** [comment]
> > Getting an error when using either of the following two methods to define an option:
> > ```python
> > @slash_command(name="opt_test")
> > async def opt_test(ctx: discord.ApplicationContext, test_option: Option(str, "Test")):
> >     await ctx.respond("test")
> > 
> > @slash_command(name="opt_test")
> > async def opt_test(ctx: discord.ApplicationContext, test_option: str = Option(description="Test")):
> >     await ctx.respond("test")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > Traceback (most recent call last):
> >   File "C:\Users\ben\PycharmProjects\BasicBot\bot.py", line 48, in <module>
> >     async def opt_test(ctx: discord.ApplicationContext, test_option: Option(str, "Test")):
> >   File "C:\Users\ben\PycharmProjects\BasicBot\venv\lib\site-packages\discord\commands\core.py", line 1560, in decorator
> >     return cls(func, **attrs)
> >   File "C:\Users\ben\PycharmProjects\BasicBot\venv\lib\site-packages\discord\commands\core.py", line 637, in __init__
> >     self.options: List[Option] = self._parse_options(params)
> >   File "C:\Users\ben\PycharmProjects\BasicBot\venv\lib\site-packages\discord\commands\core.py", line 690, in _parse_options
> >     option = Option(option, "No description provided")
> >   File "C:\Users\ben\PycharmProjects\BasicBot\venv\lib\site-packages\discord\commands\options.py", line 133, in __init__
> >     _type = SlashCommandOptionType.from_datatype(input_type)
> >   File "C:\Users\ben\PycharmProjects\BasicBot\venv\lib\site-packages\discord\enums.py", line 670, in from_datatype
> >     if datatype.__name__ in ["Member", "User"]:
> > AttributeError: 'str' object has no attribute '__name__'. Did you mean: '__ne__'?
> > ```
> 
> Are you including `from __future__ import annotations`?

Oh, whoops. Removing that resolves the issue.

**Comment by krittick** [comment]
Decorator works great, Union[TextChannel, VoiceChannel] and all the other good stuff work as well.

**Review by krittick — APPROVED** [review]

**Review by Lulalaby — APPROVED** [review]
@krittick its fucking 11pm xd 
But here we go
Yeet

**Comment by martinbndr** [comment]
Hi,
sry idk if this is the right place for it but there are issues either with the new slash option system / or the example is incorrect
Code:
```py
@client.slash_command()
@discord.option(
    "channel",
    [discord.TextChannel, discord.VoiceChannel],
    # you can specify allowed channel types by passing a list of them like this
    description="Select a channel",
)
async def testcommand(
    ctx: discord.ApplicationContext,
    channel: Union[discord.TextChannel, discord.VoiceChannel],
):
    await ctx.respond(f"Hi! You selected {channel.mention} channel.")
```

Error:
image

Exception has occurred: TypeError
issubclass() arg 1 must be a class.

Probably the example needs to be fixed

**Comment by jab416171** [comment]
@martinbndr please create a new issue here: https://github.com/Pycord-Development/pycord/issues/new/choose

**Pull request merged**
