### PR TITLE
feat: add missing AppInfo attributes

### PR DESCRIPTION
**Pull request by JustaSqu1d**
## Summary

discord/discord-api-docs#7070

## Information

- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed).
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting,
      examples, ...).

## Checklist

- [x] I have searched the open pull requests for duplicates.
- [x] If code changes were made then they have been tested.
  - [x] I have updated the documentation to reflect the changes.
- [x] If `type: ignore` comments were used, a comment is also left explaining why.
- [x] I have updated the changelog to include these changes.

### CODE REVIEW

**Comment by JustaSqu1d** [comment]
Not sure if I should list each individual attribute or group them

**Comment by plun1331** [comment]
> Not sure if I should list each individual attribute or group them in the changelog

Grouping would probably be best

**Comment by JustaSqu1d** [comment]
> > Not sure if I should list each individual attribute or group them in the changelog
> 
> Grouping would probably be best

Is what I have now good enough? I would like it to be more precise, but I cannot think of anything accurate.

**Review by plun1331 — APPROVED** [review]

**Comment by Lulalaby** [comment]
@JustaSqu1d can u resolve the merge conflict. im confused which one is correct

**Comment by JustaSqu1d** [comment]
@Lulalaby done

**Review by plun1331 — APPROVED** [review]

**Pull request merged**
