### PR TITLE
fix: options initializing with null input type

### PR DESCRIPTION
**Pull request by nexy7574**
## Summary

Previously, if for some reason an Option was created with a None `input_type` value, an error would not be raised until `on_connect` called `sync_commands()`. You can see the trouble I had to go through troubleshooting the vague error message [here](https://discord.com/channels/881207955029110855/1132206148309749830/1244683495217954876).

This two-line modification will simply raise an error if input_type is None after Option() has finished initialising.
If this is not a suitable fix, I am open to suggestions to make further modifications.

## Information

- [X] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed).
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting,
      examples, ...).

## Checklist

- [X] I have searched the open pull requests for duplicates.
- [X] If code changes were made then they have been tested.
  - [ ] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why.
- [X] I have updated the changelog to include these changes.

### CODE REVIEW

**Comment by nexy7574** [comment]
TIL `Fix` != `fix` :^)

**Review by Lulalaby — APPROVED** [review]

**Comment by plun1331** [comment]
Is it possible we could fix the underlying cause instead? `input_type` should not be `None` unless the user set it to `None`
I believe it may have to do with this method:
https://github.com/Pycord-Development/pycord/blob/abf2eeb0e1e78e2272e572b44f99a8de0c967989/discord/commands/options.py#L202-L204
It seems to be possible for it to return `None`, perhaps we should default it to a string type instead?

**Comment by nexy7574** [comment]
@plun1331 I was unsure what the root cause is and figured just patching it like this would suffice until the proper solution can actually be found. I can certainly play around and test a few things though.
If I fix the issue I'll update this PR

**Comment by nexy7574** [comment]
Okay so I just spent ages walking through `Option.__init__` manually, and have found the issue. The processing is as follows:

1. The function's argument list contains two or more `discord.ApplicationContext` or `bridge.BridgeContext` type annotations.
2. Only the first argument is expected to be a context (excluding in classes where it is `self`). As such, any arguments after are treated as options.
3. The [enum if block](https://github.com/Pycord-Development/pycord/blob/abf2eeb0e1e78e2272e572b44f99a8de0c967989/discord/commands/options.py#L196-L207) evaluates to False as, while `input_type_is_class` is evaluated to `True`, the type is not an instance of `Enum` or `DiscordEnum`. So we continue.
4. We skip past the [Converter if block](https://github.com/Pycord-Development/pycord/blob/abf2eeb0e1e78e2272e572b44f99a8de0c967989/discord/commands/options.py#L217-L220) as nContext is not a converter subclass, leading us to the else statement.
5. The first thing that is done in that try/except/else is [call from_datatype](https://github.com/Pycord-Development/pycord/blob/abf2eeb0e1e78e2272e572b44f99a8de0c967989/discord/commands/options.py#L227) with the phony context type.
6. Inside `from_datatype`, its observable that datatype is not a tuple, Member/User/nChannel/Role/Attachment/Mentionable or a standard datatype, skipping over the majority of the function.
7. We get to [the final statement](https://github.com/Pycord-Development/pycord/blob/abf2eeb0e1e78e2272e572b44f99a8de0c967989/discord/enums.py#L846-L851) which purely makes sure that if the type is __not__ one of the contexts, that `TypeError` is raised.
8. The function returns `None` as there is no explicit return, nor an `else` for the skipped `if`.
9. We then get to Option's [else of the try block](https://github.com/Pycord-Development/pycord/blob/abf2eeb0e1e78e2272e572b44f99a8de0c967989/discord/commands/options.py#L236-L248) as there  was no raised error, however `input_type` is now None.
10. No further processing is done in `__init__`, meaning the class successfully initialises with a NoneType input_type, as the rest of the references to it are merely equality comparisons, and you can compare None to anything.

**Comment by nexy7574** [comment]
Now that we know what is actually causing the error, I believe an error message is more appropriate than simply defaulting to a type of string or whatever, as clearly the developer is expecting some form of context - raising an error would very easily indicate that is not what they would receive.

**Comment by Dorukyum** [comment]
I'd take this as a temporary fix, although we are aware that the option handling system still requires heavy changes.

**Comment by nexy7574** [comment]
> although we are aware that the option handling system still requires heavy changes

Aside from a general tidy up, what sort of changes does it really need?

**Comment by Dorukyum** [comment]
> Aside from a general tidy up, what sort of changes does it really need? 

A _very thorough_ tidy up.

**Comment by nexy7574** [comment]
The docs links CI keeps failing, I don't think that's my fault is it? There's so many CI jobs to look through

**Comment by nexy7574** [comment]
Any movement on this?

**Comment by nexy7574** [comment]
> CI looks good on my end, everything passed

Turns out I was misreading the notification github was giving me, it was giving me an error on my fork itself, not the PR. All is good here.

**Comment by Dorukyum** [comment]
Upon further thought, I think we should try to solve the root issue instead. @plun1331's idea of defaulting the option type to string seems like a good solution.

**Comment by nexy7574** [comment]
> Upon further thought, I think we should try to solve the root issue instead. @plun1331's idea of defaulting the option type to string seems like a good solution.

I do still disagree with this as the user would be expecting a different type, which if then used in the code would raise an AttributeError (for example, trying `.defer()`) - I still think preventing the option from initialising at all would be significantly easier and more helpful to debug, and prevents unexpected behaviour.

Although, if the consensus is a string default, I can make that change and update this PR :+1:

**Review by Dorukyum — DISMISSED** [review]
I just realised what the actual issue is. This happens when you add an argument before ctx when you shouldn't, therefore the program should throw an error.

**Comment by nexy7574** [comment]
> I just realised what the actual issue is. This happens when you add an argument before ctx when you shouldn't, therefore the program should throw an error.

[I investigated the entire logic flow](https://github.com/Pycord-Development/pycord/pull/2464#issuecomment-2136177967), hence why I'm adamant it should be an error, not a default :+1:

**Pull request merged**
