### PR TITLE
Fix: Fix discord.errors not working

### PR DESCRIPTION
**Pull request by sevenc-nanashi**
## Summary

It fixes `discord.errors.XXX` not working.
Currently, `discord.errors` is overridden by `discord.commands.errors` because of `from .commands import *`.
So I changed to `from .commands.__init__ import *`.

## Checklist

- [x] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why
- [x] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting, examples, ...)

### CODE REVIEW

**Comment by sevenc-nanashi** [comment]
Any update on this?

**Comment by Middledot** [comment]
Could you please provide recreation code where you got this error because I can't seem to reproduce it?

**Comment by sevenc-nanashi** [comment]
@Middledot 
it was working in original discord.py, but pycord not.
88B7F74B-1E98-4AB7-82DB-15A307C029DC

**Comment by mysistersbrother** [comment]
image
I can't replicate this error but `discord.Forbidden` should still work fine regardless of this problem. This isn't even really a problem considering you aren't supposed to access things through filename paths like this. As long as you follow the docs it is fine.
https://discordpy.readthedocs.io/en/latest/api.html#discord.Forbidden
image

**Also commands shouldn't be imported in that file at all.**
I don't know how you got that error in `discord.py` because it does not import commands there. Someone added that feature in this pycord fork when it shouldn't even be there. That would mean you can just do things like `discord.Bot` instead of importing commands. In fact importing commands would become completely redundant.

The real fix to this problem is just to remove that line which imports commands into the discord folder `__init__` file.

**Review by Middledot — APPROVED** [review]
It seems that .commands.errors does override it

**Review by Dorukyum — APPROVED** [review]

**Pull request merged**
