### PR TITLE
feat: Alert when view passed is not an instance of the view

### PR DESCRIPTION
**Pull request by BaconErie**
## Summary

Developers may forget to make an instance of Models before sending it. Currently this returns a cryptic error message:
```
TypeError: to_components() missing 1 required positional argument: 'self'
```

This PR gives a more helpful error message when it detects that a class is passed instead of an object

For example, if the View model class is passed instead of a View object, there is a more helpful error:
```
InvalidArgument: The view you passed, ViewClass, should be an object, not a class. Have you forgotten parentheses?
```

This checking works for both Integrations and normal Messageable.send 

I was inspired to make this alert after someone in the Discord server got this cryptic error message, and were just missing parentheses.

## Information

- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed).
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting,
      examples, ...).

## Checklist

- [ ] I have searched the open pull requests for duplicates.
- [x] If code changes were made then they have been tested. [Test file](https://github.com/BaconErie/pycord-with-bacon/blob/test/object_checking_test.py)

- [ ] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why.

### CODE REVIEW

**Review by JustaSqu1d — COMMENTED** [review]
Why just for `view` objects? Why not other classes as well?

**Comment by Lulalaby** [comment]
This plus the comments look weird and unit test failing

**Comment by BaconErie** [comment]
> Why just for `view` objects? Why not other classes as well?

Oh yeah that's a good idea I'll add checking for the rest

> This plus the comments look weird and unit test failing

Should I remove the comment on 1692?

**Comment by BaconErie** [comment]
@JustaSqu1d @Lulalaby I'm currently working on adding object checking for `embeds`, `files`, `allowed_mentions`, and `reference` as well as `views`. 
Do you have any suggestions for what else I should add checking for?

Kwargs I've purposefully ignored:
- `content, tts, delete_after, nonce, mention_author, surpress, thread_name, username, ephemeral, wait`: Ignored because these are base Python types (str, bool, etc.)
- `thread, stickers`: Ignored because these are Discord models and cannot be created by the programmer

**Review by Lulalaby — CHANGES_REQUESTED** [review]
You pinged me

just kidding.
Remove the comments, I don't think we need them

**Review by Lulalaby — APPROVED** [review]
LGTM

**Review by JustaSqu1d — APPROVED** [review]
From personal experience, it seems like "Did you forget" is more common than "Have you forgotten." Other than that looks good to me.

**Comment by Lulalaby** [comment]
true! thanks squid

**Comment by BobDotCom** [comment]
TBH, I don't think this is needed. Literally any method on any object in python raises the same error when it is called on the class rather than an instance, I don't see why this should be any different

**Comment by BobDotCom** [comment]
TBH, I don't think this is needed. Literally any method on any object in python raises the same error when it is called on the class rather than an instance, I don't see why this should be any different

**Comment by BaconErie** [comment]
I intended for this addition to help newer users solve errors on their own and reduce clutter in the help channels, particularly since `send` is a commonly used function, parentheses are easy to miss, and questions have already been posted asking about this error.

However, I can see how this issue is pretty broad and this PR targets only a small portion of the issue.

At the end of the day, it's your call

**Comment by BobDotCom** [comment]
Maybe a more correct way to handle it would be something like this. We shouldn't raise an exception because that would violate duck typing - "If it walks like a duck and it quacks like a duck, then it must be a duck." Raising an exception would stop the execution before actually testing if the object behaves "like a duck," or in this case, "like a view instance."
```py
if not isinstance(...):
    logging.warning() # or maybe even use an actual warning?
```

**Comment by BaconErie** [comment]
I disagree with this code violating duck typing. The code only checks if the argument passed is a class; it does not do anything if the argument passed is an object. In other words, the code does not care if it is a duck or a duck imitation, it only cares if it is a duck blueprint. If it is a duck blueprint, it cannot function like a duck, and so should error.

**Comment by BobDotCom** [comment]
> I disagree with this code violating duck typing. The code only checks if the argument passed is a class; it does not do anything if the argument passed is an object. In other words, the code does not care if it is a duck or a duck imitation, it only cares if it is a duck blueprint. If it is a duck blueprint, it cannot function like a duck, and so should error.

Regardless I still think a warning would suffice, it has the benefits with less downsides

**Comment by Lulalaby** [comment]
On request of erie

**Pull request closed without merging**
