### PR TITLE
Update intents for message intent becoming privileged

### PR DESCRIPTION
**Pull request by BobDotCom**
Moved from #328.

### CODE REVIEW

**Review by Dorukyum — APPROVED** [review]

**Comment by Lulalaby** [comment]
uhm that's too fast.

**Comment by Middledot** [comment]
Shouldn't the intent be called guild_message_content or smth?

**Comment by Lulalaby** [comment]
no

**Comment by Lulalaby** [comment]
This reflects the api

**Comment by Middledot** [comment]
but you can still receive the event just not certain fields?

**Comment by Lulalaby** [comment]
You didn't read the announcements, did you?

**Comment by Middledot** [comment]
Which announcement exactly?

**Pull request merged**
