### PR TITLE
Added: discord.Timestamp and discord.TimestampType

### PR DESCRIPTION
**Pull request by martinbndr**
## Summary

I created a little Class that lets users create a discord formatted timestamp.

discord.Timestamp
discord.TimestampType

## Information

- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed).
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting, examples, ...).

## Checklist

- [ ] I have searched the open pull requests for duplicates.
- [ ] If code changes were made then they have been tested.
  - [ ] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why.

### CODE REVIEW

**Comment by martinbndr** [comment]
Lol why are there other commits from other pull requests of me inside here 👀

**Comment by martinbndr** [comment]
This commit is the one that adds the new stuff:
https://github.com/Pycord-Development/pycord/pull/1627/commits/fd31ddfc82d556bacde692e79d86c390dec2f89e

**Comment by plun1331** [comment]
A class is excessive for this functionality. and such a thing already exists in `discord.utils`
https://github.com/Pycord-Development/pycord/blob/7c8cd56c4a9d1ae7900578db351c24e508776de0/discord/utils.py#L1035-L1036

**Comment by martinbndr** [comment]
> A class is excessive for this functionality. and such a thing already exists in `discord.utils`
> 
> https://github.com/Pycord-Development/pycord/blob/7c8cd56c4a9d1ae7900578db351c24e508776de0/discord/utils.py#L1035-L1036

Oh wow sry didn´t notice hmm

**Pull request closed without merging**
