### PR TITLE
feat: implement `(Sync)WebhookMessage.thread`

### PR DESCRIPTION
**Pull request by Def-Try**
## Summary

Related to issue #2298
Fixes webhook messages assuming that their `_thread_id` can not be `None` (spoiler; it can)

## Information

- [x] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed).
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting,
      examples, ...).

## Checklist

- [x] I have searched the open pull requests for duplicates.
- [ ] If code changes were made then they have been tested.
  - [ ] I have updated the documentation to reflect the changes.
- [x] If `type: ignore` comments were used, a comment is also left explaining why.
- [x] I have updated the changelog to include these changes.

### CODE REVIEW

**Review by Lulalaby — DISMISSED** [review]

**Comment by Dorukyum** [comment]
Your changes might fix the issue but I think the best way to approach this is to create a property called `WebhookMessage.thread_id` instead. That would get rid of the duplicate code. What do you think?

**Comment by Def-Try** [comment]
so, something like that? never worked on big projects (and typing to be honest), so my style may be weird

**Comment by Def-Try** [comment]
i do not know why docs/readthedocs.org:pycord check keeps failing
everything else on the other hand appears to be ok
image
image
image

**Comment by Lulalaby** [comment]
https://readthedocs.org/projects/pycord/builds/23121803/ look here

**Comment by Def-Try** [comment]
> https://readthedocs.org/projects/pycord/builds/23121803/ look here

all i see here is an `AttributeError: None` with no information about what caused it (in pycord code i mean) and a lot of warnings

**Comment by Dorukyum** [comment]
I went ahead and replaced your solution with adding `WebhookMessage.thread` and `SyncWebhookMessage.thread` properties. Not sure if this is necessary or if this is the best solution, but it's the cleanest solution that came to my mind.

Requires testing.

**Comment by Dorukyum** [comment]
After looking with a clear mind into the issue I realized none of these changes were necessary. Will open a new pr with just 2 lines changed. Thanks nevertheless.

**Pull request closed without merging**
