### PR TITLE
Fix oldest_first not respecting oldest->newest entry

### PR DESCRIPTION
**Pull request by champymarty**
## Information

- [x] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed).
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting,
      examples, ...).

## Checklist

- [x] I have searched the open pull requests for duplicates.
- [x] If code changes were made then they have been tested.
  - [ ] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why.
- [ ] I have updated the changelog to include these changes.

### CODE REVIEW

**Comment by champymarty** [comment]
what will happen with this PR. Do I need to change anything ?

**Comment by Lulalaby** [comment]
The implementation of audit logs is completely wrong, we have to redo it completely

**Comment by champymarty** [comment]
What is completely wrong ? I am using it right now in my bot

**Comment by Lulalaby** [comment]
our implementation
we're gonna rework it later in a different pr

**Pull request closed without merging**
