### PR TITLE
Made `AutocompleteContext.cog` `ApplicationContext.cog` and `ApplicationContext.voice_client` into one liners.

### PR DESCRIPTION
**Pull request by Sengolda**
## Summary

Makes `AutocompleteContext.cog` `ApplicationContext.cog` and `ApplicationContext.voice_client` into one liners.

## Checklist

- [x] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting, examples, ...)

### CODE REVIEW

**Comment by nerdguyahmad** [comment]
The former is much cleaner and [faster](https://stackoverflow.com/questions/2909423/is-it-bad-practice-to-use-pythons-getattr-extensively). (FYI, Discord.py does takes care about these small optimizations)

This one is less cleaner and slower too. Besides, It is done the former way everywhere in codebase and seems inconsistent to use `getattr` for no reason.

**Comment by ultrabear** [comment]
Its possible to make this a oneliner without getattr but even then it just makes the code less readable.
This doesnt feel like a path that would need to be super fast in the first place, write readable code first, and only optimize if its an actual issue.

**Comment by Dorukyum** [comment]
Adding on to ultrabear's comment, this is also inconsistent with the rest of the library which we dont want to change the style of.

**Comment by zeffo** [comment]
`getattr` actually performs marginally better:
https://gist.github.com/zeffo/cfd384e429ab49702a240c692cb7ba61

Observations:
- getattr performs better when the attribute exists by an average of `0.012221200000000043`
- Logical check performs better when the attribute doesn't exist by an average of `0.011293399999999953`

Which makes getattr faster by `0.0009278000000000897` seconds. 

data


As for the cleanliness bit; I personally don't think there's anything unclean with using getattr, it's format is a mirror of `dict.get` which has been used in the library.

**Pull request closed without merging**
