### PR TITLE
fix!: Reflect the api for getting bans correctly

### PR DESCRIPTION
**Pull request by Lulalaby**

### CODE REVIEW

**Comment by Lulalaby** [comment]
@plun1331 do you remember if we deprecated it alr?

**Comment by plun1331** [comment]
> @plun1331 do you remember if we deprecated it alr?

No clue, docs would mention it

**Comment by UP929312** [comment]
@Lulalaby Any updates on this too?

**Comment by Lulalaby** [comment]
@plun1331 ping pong

**Review by plun1331 — APPROVED** [review]

**Pull request merged**
