### PR TITLE
Text in voice

### PR DESCRIPTION
**Pull request by BobDotCom**
## Summary

Implement text in voice - the ability to send messages to voice channels.

## Checklist

- [x] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [x] If `type: ignore` comments were used, a comment is also left explaining why
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting, examples, ...)

### CODE REVIEW

**Review by Lulalaby — CHANGES_REQUESTED** [review]
This does not only implement text in voice.

This PR is out of scope with the additional changes and therefore a bad example.

Considering split of pr

**Comment by BobDotCom** [comment]
> This does not only implement text in voice.
> 
> This PR is out of scope with the additional changes and therefore a bad example.
> 
> Considering split of pr

It does though....? There's no changes besides text-in-voice.

**Comment by EmreTech** [comment]
I'm confused about this: how do you even send text messages in Voice Channels?
Oh wait does Discord now bundle "Text Channels" with Voice Channels?

**Comment by Lulalaby** [comment]
> I'm confused about this: how do you even send text messages in Voice Channels?
> Oh wait does Discord now bundle "Text Channels" with Voice Channels?

Voice channel just have a API side lock. They are basically text channel since a while

**Comment by Lulalaby** [comment]
> > This does not only implement text in voice.
> > 
> > This PR is out of scope with the additional changes and therefore a bad example.
> > 
> > Considering split of pr
> 
> It does though....? There's no changes besides text-in-voice.

I see changes in the deletion strategy

**Comment by BobDotCom** [comment]
> > > This does not only implement text in voice.
> > > This PR is out of scope with the additional changes and therefore a bad example.
> > > Considering split of pr
> > 
> > 
> > It does though....? There's no changes besides text-in-voice.
> 
> I see changes in the deletion strategy

No changes, I threw code into a helper method to be re-used.

**Comment by Lulalaby** [comment]
Oh okay. Then LGTM

**Review by Lulalaby — APPROVED** [review]

**Review by Lulalaby — APPROVED** [review]

**Review by Dorukyum — APPROVED** [review]

**Pull request merged**
