### PR TITLE
fix: Duplication in bridge command help

### PR DESCRIPTION
**Pull request by Blue-Robin-Taken**
## Summary
This pull request is for the issue https://github.com/Pycord-Development/pycord/issues/2306

## Information

- [x] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed).
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting,
      examples, ...).

## Checklist

- [x] I have searched the open pull requests for duplicates.
- [x] If code changes were made then they have been tested.
  - [ ] I have updated the documentation to reflect the changes.
- [x] If `type: ignore` comments were used, a comment is also left explaining why.
- [x] I have updated the changelog to include these changes.

### CODE REVIEW

**Comment by Blue-Robin-Taken** [comment]
Just need to add docs and changelog

**Review by Lulalaby — APPROVED** [review]

**Comment by solaluset** [comment]
This breaks the command if ext.bridge is not imported:
```
Ignoring exception in command help:
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/tests/lib/python3.11/site-packages/discord/ext/commands/core.py", line 180, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/tests/lib/python3.11/site-packages/discord/ext/commands/help.py", line 858, in command_callback
    return await self.send_bot_help(mapping)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/tests/lib/python3.11/site-packages/discord/ext/commands/help.py", line 1074, in send_bot_help
    self.add_indented_commands(commands, heading=category, max_size=max_size)
  File "/data/data/com.termux/files/home/tests/lib/python3.11/site-packages/discord/ext/commands/help.py", line 1000, in add_indented_commands
    command, discord.ext.bridge.core.BridgeExtCommand
             ^^^^^^^^^^^^^^^^^^
AttributeError: module 'discord.ext' has no attribute 'bridge'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/data/com.termux/files/home/tests/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 349, in invoke
    await ctx.command.invoke(ctx)
  File "/data/data/com.termux/files/home/tests/lib/python3.11/site-packages/discord/ext/commands/core.py", line 959, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/data/data/com.termux/files/home/tests/lib/python3.11/site-packages/discord/ext/commands/core.py", line 189, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: module 'discord.ext' has no attribute 'bridge'
```

**Comment by Blue-Robin-Taken** [comment]
oh frick

**Comment by Blue-Robin-Taken** [comment]
that uh

**Pull request closed without merging**
