### PR TITLE
Improving a sentence in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by ImNimboss**
The original sentence was incorrect because the Discord API server is not *under* #python_discord-py, rather it is the other way around.

## Summary

This PR fixes a sentence grammatically in CONTRIBUTING.md

## Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] This PR is **not** a code change (e.g. documentation, README, typehinting, examples, ...)

### CODE REVIEW

**Comment by ChickenDevs** [comment]
Technically the old one was still correct, just could've used a comma

**Comment by ChickenDevs** [comment]
Also, maybe we consider removing that line all together. Danny has already said he wont give pycord a channel in DAPI, and people would be confused if we used the discord,py channel

**Comment by Lulalaby** [comment]
> Also, maybe we consider removing that line all together. Danny has already said he wont give pycord a channel in DAPI, and people would be confused if we used the discord,py channel

Here goes dapi again..

**Review by Lulalaby — CHANGES_REQUESTED** [review]
Remove the line and change the invite link on line 11 to /pycord

**Comment by ImNimboss** [comment]
> Remove the line and change the invite link on line 11 to /pycord

crap lol I deleted my fork, ill create a new PR

**Pull request closed without merging**
