### PR TITLE
feat: :sparkles: Add creator monetization analytics perms (`1 << 41`)

### PR DESCRIPTION
**Pull request by Paillat-dev**
## Summary

See https://discord.com/developers/docs/topics/permissions#:~:text=VIEW_CREATOR_MONETIZATION_ANALYTICS
I don't have setup to test this so pls if you think it needs to be tested, wait for someone to test it.

## Information

- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed).
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting,
      examples, ...).

## Checklist

- [x] I have searched the open pull requests for duplicates.
- [ ] If code changes were made then they have been tested.
  - [x] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why.
- [x] I have updated the changelog to include these changes.

### CODE REVIEW

**Comment by NeloBlivion** [comment]
if you want, you can just roll all the missing perms into a single PR

**Comment by Paillat-dev** [comment]
@NeloBlivion Sure, didn't do it in the first place as I felt like there might be conflicts in the soundboard one / wanting to implement soudboard features entirely in one go.

**Comment by NeloBlivion** [comment]
Soundboard's kinda been in limbo for a while so you can just implement perms first, if you wanna tackle the rest of soundboard separately then go for it

**Comment by Paillat-dev** [comment]
Implemented in #2620

**Pull request closed without merging**
