### PR TITLE
Fix broken cog attribute

### PR DESCRIPTION
**Pull request by Middledot**
## Summary
Hopefully the last fix. Tested with code in #1593.

Edit: also fixes bug with subcommands' mentions.

## Information

- [x] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed).
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting, examples, ...).

## Checklist

- [x] I have searched the open pull requests for duplicates.
- [x] If code changes were made then they have been tested.
  - [ ] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why.

### CODE REVIEW

**Review by BobDotCom — DISMISSED** [review]

**Comment by NeloBlivion** [comment]
Testing, this fixes the long standing `get_overridden_method` issue, however it breaks subcommands in cogs

```py
Traceback (most recent call last):
  File "C:\Users\me\Documents\!TestBenchd\venv\lib\site-packages\discord\commands\core.py", line 747, in _match_option_param_names
    p_name, p_obj = next(params)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\me\Documents\!TestBenchd\venv\lib\site-packages\discord\cog.py", line 745, in _load_from_module_spec
    setup(self)
  File "C:\Users\me\Documents\!TestBenchd\cogs\example.py", line 27, in setup
    bot.add_cog(Example(bot))
  File "C:\Users\me\Documents\!TestBenchd\venv\lib\site-packages\discord\cog.py", line 618, in add_cog
    cog = cog._inject(self)
  File "C:\Users\me\Documents\!TestBenchd\venv\lib\site-packages\discord\cog.py", line 516, in _inject
    command._set_cog(self)
  File "C:\Users\me\Documents\!TestBenchd\venv\lib\site-packages\discord\commands\core.py", line 1272, in _set_cog
    subcommand._set_cog(cog)
  File "C:\Users\me\Documents\!TestBenchd\venv\lib\site-packages\discord\commands\core.py", line 575, in _set_cog
    self.cog = cog
  File "C:\Users\me\Documents\!TestBenchd\venv\lib\site-packages\discord\commands\core.py", line 778, in cog
    self._validate_parameters()
  File "C:\Users\me\Documents\!TestBenchd\venv\lib\site-packages\discord\commands\core.py", line 669, in _validate_parameters
    self.options: List[Option] = self._match_option_param_names(params, kwop)
  File "C:\Users\me\Documents\!TestBenchd\venv\lib\site-packages\discord\commands\core.py", line 749, in _match_option_param_names
    raise ClientException("Too many arguments passed to the options kwarg.")
discord.errors.ClientException: Too many arguments passed to the options kwarg.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\me\Documents\!TestBenchd\cogs\owner.py", line 111, in reload
    self.bot.reload_extension(cog)
  File "C:\Users\me\Documents\!TestBenchd\venv\lib\site-packages\discord\cog.py", line 1069, in reload_extension
    self.load_extension(name)
  File "C:\Users\me\Documents\!TestBenchd\venv\lib\site-packages\discord\cog.py", line 869, in load_extension
    self._load_from_module_spec(spec, name)
  File "C:\Users\me\Documents\!TestBenchd\venv\lib\site-packages\discord\cog.py", line 750, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.errors.ExtensionFailed: Extension 'cogs.example' raised an error: ClientException: Too many arguments passed to the options kwarg.
```

**Comment by NeloBlivion** [comment]
caused by this part in `add_command`
```py
        if command.cog is MISSING:
            command.cog = self.cog
```
which happens to be the fix to overridden_method...

**Comment by NeloBlivion** [comment]
Looking further, the entire `_match_option_param_names` in commands.core may be broken; but most of the time it's never called so you wouldn't notice.

**Comment by Middledot** [comment]
If we just don't set the cog of the subcommand if the parent doesn't have it set, we don't have any duplicated option checking. If the group is not in a cog, the group is added to the bot before the subcommands are added to the group, so by the time they (the subcommands) are added, they have the cog set immediately:
https://github.com/Pycord-Development/pycord/blob/303a5849e91cdc80029539a36ec8f345ad5c90f0/discord/bot.py#L126-L127
If the group is in a cog, the subcommands are added before the group has its cog set, so the group will instead set the cog when it gets it:
https://github.com/Pycord-Development/pycord/blob/303a5849e91cdc80029539a36ec8f345ad5c90f0/discord/cog.py#L531
https://github.com/Pycord-Development/pycord/blob/303a5849e91cdc80029539a36ec8f345ad5c90f0/discord/commands/core.py#L1339-L1342
Either way, `_validate_parameters` is only ever called once.

Should probably still be tested in case.
Also SlashCommandGroup uses MISSING for the cog attr now

**Comment by NeloBlivion** [comment]
Have been testing and it looks all fixed for now

**Review by BobDotCom — APPROVED** [review]

**Pull request merged**
