### PR TITLE
Bugfix/modify mypy ci

### LINKED ISSUE #788: mypy CI is not working!
### Summary

github workflow's mypy CI is not working. All errors, including fatal, are ignored.

### Reproduction Steps

You can see in the latest github workflow log.
<https://github.com/Pycord-Development/pycord/runs/4812755113?check_suite_focus=true>

```log
Run mypy --ignore-missing-imports --install-types --non-interactive . || true
  mypy --ignore-missing-imports --install-types --non-interactive . || true
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.10.1/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.10.1/x64/lib
discord/commands/core.py:167: error: Invalid "type: ignore" comment
Found 5 errors in 1 file (errors prevented further checking)
discord/commands/core.py:186: error: Invalid "type: ignore" comment
discord/commands/core.py:193: error: Invalid "type: ignore" comment
discord/commands/core.py:229: error: Invalid "type: ignore" comment
discord/commands/core.py:632: error: Invalid "type: ignore" comment
```

This is also checked on my envirnment.
( `pip install mypy` , mypy version is 0.931 )

```sh
pip install mypy
```

```sh
 % mypy --version
mypy 0.931
```

Run mypy

```sh
 % mkdir --parents --verbose .mypy_cache
 % mypy --ignore-missing-imports --install-types --non-interactive .
```

### Minimal Reproducible Code

_No response_

### Expected Results

```sh
 % mypy --ignore-missing-imports --install-types --non-interactive .
Success: no issues found in 152 source files
```

### Actual Results

<https://github.com/Pycord-Development/pycord/runs/4812755113?check_suite_focus=true>

image

```sh
 % mypy --ignore-missing-imports --install-types --non-interactive .
discord/commands/core.py:167: error: Invalid "type: ignore" comment
discord/commands/core.py:186: error: Invalid "type: ignore" comment
discord/commands/core.py:193: error: Invalid "type: ignore" comment
discord/commands/core.py:229: error: Invalid "type: ignore" comment
discord/commands/core.py:632: error: Invalid "type: ignore" comment
Found 5 errors in 1 file (errors prevented further checking)
```

### Intents

Not bot issue

### System Information

```sh
 % python -m discord -v
- Python v3.8.12-final
- py-cord v2.0.0-alpha
    - py-cord pkg_resources: v2.0.0a4793+gf8832608
- aiohttp v3.8.1
- system info: Linux 5.11.0-46-generic #51~20.04.1-Ubuntu SMP Fri Jan 7 06:51:40 UTC 2022
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by pollenjp**
## Summary

fix #788 

Current mypy CI ignore all errors including fatal one because of `|| true` .

```sh
mypy --ignore-missing-imports --install-types --non-interactive . || true
```

Fatal errors prevented further checking.
image

I fixed `type: ignore` comment with explaining why. That solves the fatal errors.

But, mypy returns normal errors by further checking.

Error log gist: <https://gist.github.com/pollenjp/6bae2f13181abfeb4ef5ed11cc07c337>

Temporally, to ignore normal errors I introduced `mypy.ini` file and added `ignore_errors = True` .

```sh
 % mypy --ignore-missing-imports --install-types --non-interactive .
Success: no issues found in 152 source files
```

## Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why
- [x] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] This PR is **not** a code change (e.g. documentation, README, typehinting, examples, ...)

### CODE REVIEW

**Review by Dorukyum — APPROVED** [review]

**Comment by Dorukyum** [comment]
Please make sure this is tested.

**Comment by pollenjp** [comment]
How can I test? I can't find some specification.

**Comment by pollenjp** [comment]
☝️  This CI check becomes substitude of a test because my change doesn't have an effect on library behavior.
<https://github.com/Pycord-Development/pycord/runs/4818567545?check_suite_focus=true>

**Comment by pollenjp** [comment]
Fix conflicts with current master branch.

**Review by Middledot — APPROVED** [review]
idk about the .ini stuff but everything else looks good

**Review by Lulalaby — APPROVED** [review]

**Pull request merged**
