### PR TITLE
Add Interaction.respond

### PR DESCRIPTION
**Pull request by NarmyOnDiscord**
## Summary
Add a function to respond to an Interaction more convenient 

## Checklist

- [x] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [ ] If `type: ignore` comments were used, a comment is also left explaining why
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, typehinting, examples, ...)

## Aditional Information 
I just added an helpstring to the new function, I have not changed any docs files, since I'm not sure how to add it

### CODE REVIEW

**Comment by mcbabo** [comment]
looks good

**Comment by krittick** [comment]
Interaction already has discrete methods to handle responses and this shortcut method doesn't make much sense to add here. While it makes sense for `ApplicationContext` to have a `respond()` method, we should avoid adding further ambiguity to the base `Interaction` class and instead require the user to specifically make the choice whether to use a response or followup.

There are also open discussions around race conditions introduced by methods like this, which would need to first be resolved to even consider this.

**Comment by Dorukyum** [comment]
Thanks for the pr but I agree with Krittick.

> Interaction already has discrete methods to handle responses and this shortcut method doesn't make much sense to add here. While it makes sense for `ApplicationContext` to have a `respond()` method, we should avoid adding further ambiguity to the base `Interaction` class and instead require the user to specifically make the choice whether to use a response or followup.
> 
> There are also open discussions around race conditions introduced by methods like this, which would need to first be resolved to even consider this.

**Comment by krittick** [comment]
Closing this as the consensus is not to add this at this time.

**Pull request closed without merging**
