### PR TITLE
Use Python syntax in slash_options.py

### PR DESCRIPTION
**Pull request by cclauss**
$ `flake8`
```
./examples/app_commands/slash_options.py:13:23: F722 syntax error in forward annotation 'Enter your name'
    name: Option(str, "Enter your name"),
                      ^
./examples/app_commands/slash_options.py:14:25: F722 syntax error in forward annotation 'Choose your gender'
    gender: Option(str, "Choose your gender", choices=["Male", "Female", "Other"]),
                        ^
./examples/app_commands/slash_options.py:14:56: F821 undefined name 'Male'
    gender: Option(str, "Choose your gender", choices=["Male", "Female", "Other"]),
                                                       ^
./examples/app_commands/slash_options.py:14:64: F821 undefined name 'Female'
    gender: Option(str, "Choose your gender", choices=["Male", "Female", "Other"]),
                                                               ^
./examples/app_commands/slash_options.py:14:74: F821 undefined name 'Other'
    gender: Option(str, "Choose your gender", choices=["Male", "Female", "Other"]),
                                                                         ^
./examples/app_commands/slash_options.py:15:22: F722 syntax error in forward annotation 'Enter your age'
    age: Option(int, "Enter your age", required=False, default=18),
                     ^
3     F722 syntax error in forward annotation 'Enter your name'
3     F821 undefined name 'Male'
6
```

## Checklist

- [x] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Review by jgayfer — COMMENTED** [review]
Probably worth holding off on changes like this until a linter is setup.

**Comment by CodeWithSwastik** [comment]
Linters won't like this syntax since it's an Object in annotations.

**Comment by cclauss** [comment]
The linter (from Python Code Quality Authority) knows all about annotations and is saying that these are syntax errors in annotations.  http://mypy-lang.org/ generates similar results.

**Comment by CodeWithSwastik** [comment]
As I said before, linters don't like this syntax so no point in linting 🤦

**Pull request closed without merging**
